package org.zcgewu.study.soa.doctor.po;

import java.io.Serializable;
import java.util.Date;

public class DoctorAppRole implements Serializable {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_doctor_app_role.doctor_app_role_uid
     *
     * @mbggenerated
     */
    private Integer doctorAppRoleUid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_doctor_app_role.doctor_uid
     *
     * @mbggenerated
     */
    private Integer doctorUid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_doctor_app_role.app_role_uid
     *
     * @mbggenerated
     */
    private Integer appRoleUid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_doctor_app_role.create_time
     *
     * @mbggenerated
     */
    private Date createTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_doctor_app_role.update_time
     *
     * @mbggenerated
     */
    private Date updateTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table tb_doctor_app_role
     *
     * @mbggenerated
     */
    private static final long serialVersionUID = 1L;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_doctor_app_role.doctor_app_role_uid
     *
     * @return the value of tb_doctor_app_role.doctor_app_role_uid
     *
     * @mbggenerated
     */
    public Integer getDoctorAppRoleUid() {
        return doctorAppRoleUid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_doctor_app_role.doctor_app_role_uid
     *
     * @param doctorAppRoleUid the value for tb_doctor_app_role.doctor_app_role_uid
     *
     * @mbggenerated
     */
    public void setDoctorAppRoleUid(Integer doctorAppRoleUid) {
        this.doctorAppRoleUid = doctorAppRoleUid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_doctor_app_role.doctor_uid
     *
     * @return the value of tb_doctor_app_role.doctor_uid
     *
     * @mbggenerated
     */
    public Integer getDoctorUid() {
        return doctorUid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_doctor_app_role.doctor_uid
     *
     * @param doctorUid the value for tb_doctor_app_role.doctor_uid
     *
     * @mbggenerated
     */
    public void setDoctorUid(Integer doctorUid) {
        this.doctorUid = doctorUid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_doctor_app_role.app_role_uid
     *
     * @return the value of tb_doctor_app_role.app_role_uid
     *
     * @mbggenerated
     */
    public Integer getAppRoleUid() {
        return appRoleUid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_doctor_app_role.app_role_uid
     *
     * @param appRoleUid the value for tb_doctor_app_role.app_role_uid
     *
     * @mbggenerated
     */
    public void setAppRoleUid(Integer appRoleUid) {
        this.appRoleUid = appRoleUid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_doctor_app_role.create_time
     *
     * @return the value of tb_doctor_app_role.create_time
     *
     * @mbggenerated
     */
    public Date getCreateTime() {
        return createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_doctor_app_role.create_time
     *
     * @param createTime the value for tb_doctor_app_role.create_time
     *
     * @mbggenerated
     */
    public void setCreateTime(Date createTime) {
        this.createTime = createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_doctor_app_role.update_time
     *
     * @return the value of tb_doctor_app_role.update_time
     *
     * @mbggenerated
     */
    public Date getUpdateTime() {
        return updateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_doctor_app_role.update_time
     *
     * @param updateTime the value for tb_doctor_app_role.update_time
     *
     * @mbggenerated
     */
    public void setUpdateTime(Date updateTime) {
        this.updateTime = updateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_doctor_app_role
     *
     * @mbggenerated
     */
    @Override
    public boolean equals(Object that) {
        if (this == that) {
            return true;
        }
        if (that == null) {
            return false;
        }
        if (getClass() != that.getClass()) {
            return false;
        }
        DoctorAppRole other = (DoctorAppRole) that;
        return (this.getDoctorAppRoleUid() == null ? other.getDoctorAppRoleUid() == null : this.getDoctorAppRoleUid().equals(other.getDoctorAppRoleUid()))
            && (this.getDoctorUid() == null ? other.getDoctorUid() == null : this.getDoctorUid().equals(other.getDoctorUid()))
            && (this.getAppRoleUid() == null ? other.getAppRoleUid() == null : this.getAppRoleUid().equals(other.getAppRoleUid()))
            && (this.getCreateTime() == null ? other.getCreateTime() == null : this.getCreateTime().equals(other.getCreateTime()))
            && (this.getUpdateTime() == null ? other.getUpdateTime() == null : this.getUpdateTime().equals(other.getUpdateTime()));
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_doctor_app_role
     *
     * @mbggenerated
     */
    @Override
    public int hashCode() {
        final int prime = 31;
        int result = 1;
        result = prime * result + ((getDoctorAppRoleUid() == null) ? 0 : getDoctorAppRoleUid().hashCode());
        result = prime * result + ((getDoctorUid() == null) ? 0 : getDoctorUid().hashCode());
        result = prime * result + ((getAppRoleUid() == null) ? 0 : getAppRoleUid().hashCode());
        result = prime * result + ((getCreateTime() == null) ? 0 : getCreateTime().hashCode());
        result = prime * result + ((getUpdateTime() == null) ? 0 : getUpdateTime().hashCode());
        return result;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_doctor_app_role
     *
     * @mbggenerated
     */
    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder();
        sb.append(getClass().getSimpleName());
        sb.append(" [");
        sb.append("Hash = ").append(hashCode());
        sb.append(", doctorAppRoleUid=").append(doctorAppRoleUid);
        sb.append(", doctorUid=").append(doctorUid);
        sb.append(", appRoleUid=").append(appRoleUid);
        sb.append(", createTime=").append(createTime);
        sb.append(", updateTime=").append(updateTime);
        sb.append(", serialVersionUID=").append(serialVersionUID);
        sb.append("]");
        return sb.toString();
    }
}