package org.zcgewu.study.soa.doctor.po;

import java.util.ArrayList;
import java.util.Date;
import java.util.List;

public class DoctorAppRoleExample {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table tb_doctor_app_role
     *
     * @mbggenerated
     */
    protected String orderByClause;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table tb_doctor_app_role
     *
     * @mbggenerated
     */
    protected boolean distinct;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table tb_doctor_app_role
     *
     * @mbggenerated
     */
    protected List<Criteria> oredCriteria;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table tb_doctor_app_role
     *
     * @mbggenerated
     */
    protected Integer limitStart;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table tb_doctor_app_role
     *
     * @mbggenerated
     */
    protected Integer limitEnd;

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_doctor_app_role
     *
     * @mbggenerated
     */
    public DoctorAppRoleExample() {
        oredCriteria = new ArrayList<Criteria>();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_doctor_app_role
     *
     * @mbggenerated
     */
    public void setOrderByClause(String orderByClause) {
        this.orderByClause = orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_doctor_app_role
     *
     * @mbggenerated
     */
    public String getOrderByClause() {
        return orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_doctor_app_role
     *
     * @mbggenerated
     */
    public void setDistinct(boolean distinct) {
        this.distinct = distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_doctor_app_role
     *
     * @mbggenerated
     */
    public boolean isDistinct() {
        return distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_doctor_app_role
     *
     * @mbggenerated
     */
    public List<Criteria> getOredCriteria() {
        return oredCriteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_doctor_app_role
     *
     * @mbggenerated
     */
    public void or(Criteria criteria) {
        oredCriteria.add(criteria);
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_doctor_app_role
     *
     * @mbggenerated
     */
    public Criteria or() {
        Criteria criteria = createCriteriaInternal();
        oredCriteria.add(criteria);
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_doctor_app_role
     *
     * @mbggenerated
     */
    public Criteria createCriteria() {
        Criteria criteria = createCriteriaInternal();
        if (oredCriteria.size() == 0) {
            oredCriteria.add(criteria);
        }
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_doctor_app_role
     *
     * @mbggenerated
     */
    protected Criteria createCriteriaInternal() {
        Criteria criteria = new Criteria();
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_doctor_app_role
     *
     * @mbggenerated
     */
    public void clear() {
        oredCriteria.clear();
        orderByClause = null;
        distinct = false;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_doctor_app_role
     *
     * @mbggenerated
     */
    public void setLimitStart(Integer limitStart) {
        this.limitStart=limitStart;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_doctor_app_role
     *
     * @mbggenerated
     */
    public Integer getLimitStart() {
        return limitStart;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_doctor_app_role
     *
     * @mbggenerated
     */
    public void setLimitEnd(Integer limitEnd) {
        this.limitEnd=limitEnd;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_doctor_app_role
     *
     * @mbggenerated
     */
    public Integer getLimitEnd() {
        return limitEnd;
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table tb_doctor_app_role
     *
     * @mbggenerated
     */
    protected abstract static class GeneratedCriteria {
        protected List<Criterion> criteria;

        protected GeneratedCriteria() {
            super();
            criteria = new ArrayList<Criterion>();
        }

        public boolean isValid() {
            return criteria.size() > 0;
        }

        public List<Criterion> getCriteria() {
            return criteria;
        }

        protected void addCriterion(String condition) {
            if (condition == null) {
                throw new RuntimeException("Value for condition cannot be null");
            }
            criteria.add(new Criterion(condition));
        }

        protected void addCriterion(String condition, Object value, String property) {
            if (value == null) {
                throw new RuntimeException("Value for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value));
        }

        protected void addCriterion(String condition, Object value1, Object value2, String property) {
            if (value1 == null || value2 == null) {
                throw new RuntimeException("Between values for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value1, value2));
        }

        public Criteria andDoctorAppRoleUidIsNull() {
            addCriterion("doctor_app_role_uid is null");
            return (Criteria) this;
        }

        public Criteria andDoctorAppRoleUidIsNotNull() {
            addCriterion("doctor_app_role_uid is not null");
            return (Criteria) this;
        }

        public Criteria andDoctorAppRoleUidEqualTo(Integer value) {
            addCriterion("doctor_app_role_uid =", value, "doctorAppRoleUid");
            return (Criteria) this;
        }

        public Criteria andDoctorAppRoleUidNotEqualTo(Integer value) {
            addCriterion("doctor_app_role_uid <>", value, "doctorAppRoleUid");
            return (Criteria) this;
        }

        public Criteria andDoctorAppRoleUidGreaterThan(Integer value) {
            addCriterion("doctor_app_role_uid >", value, "doctorAppRoleUid");
            return (Criteria) this;
        }

        public Criteria andDoctorAppRoleUidGreaterThanOrEqualTo(Integer value) {
            addCriterion("doctor_app_role_uid >=", value, "doctorAppRoleUid");
            return (Criteria) this;
        }

        public Criteria andDoctorAppRoleUidLessThan(Integer value) {
            addCriterion("doctor_app_role_uid <", value, "doctorAppRoleUid");
            return (Criteria) this;
        }

        public Criteria andDoctorAppRoleUidLessThanOrEqualTo(Integer value) {
            addCriterion("doctor_app_role_uid <=", value, "doctorAppRoleUid");
            return (Criteria) this;
        }

        public Criteria andDoctorAppRoleUidIn(List<Integer> values) {
            addCriterion("doctor_app_role_uid in", values, "doctorAppRoleUid");
            return (Criteria) this;
        }

        public Criteria andDoctorAppRoleUidNotIn(List<Integer> values) {
            addCriterion("doctor_app_role_uid not in", values, "doctorAppRoleUid");
            return (Criteria) this;
        }

        public Criteria andDoctorAppRoleUidBetween(Integer value1, Integer value2) {
            addCriterion("doctor_app_role_uid between", value1, value2, "doctorAppRoleUid");
            return (Criteria) this;
        }

        public Criteria andDoctorAppRoleUidNotBetween(Integer value1, Integer value2) {
            addCriterion("doctor_app_role_uid not between", value1, value2, "doctorAppRoleUid");
            return (Criteria) this;
        }

        public Criteria andDoctorUidIsNull() {
            addCriterion("doctor_uid is null");
            return (Criteria) this;
        }

        public Criteria andDoctorUidIsNotNull() {
            addCriterion("doctor_uid is not null");
            return (Criteria) this;
        }

        public Criteria andDoctorUidEqualTo(Integer value) {
            addCriterion("doctor_uid =", value, "doctorUid");
            return (Criteria) this;
        }

        public Criteria andDoctorUidNotEqualTo(Integer value) {
            addCriterion("doctor_uid <>", value, "doctorUid");
            return (Criteria) this;
        }

        public Criteria andDoctorUidGreaterThan(Integer value) {
            addCriterion("doctor_uid >", value, "doctorUid");
            return (Criteria) this;
        }

        public Criteria andDoctorUidGreaterThanOrEqualTo(Integer value) {
            addCriterion("doctor_uid >=", value, "doctorUid");
            return (Criteria) this;
        }

        public Criteria andDoctorUidLessThan(Integer value) {
            addCriterion("doctor_uid <", value, "doctorUid");
            return (Criteria) this;
        }

        public Criteria andDoctorUidLessThanOrEqualTo(Integer value) {
            addCriterion("doctor_uid <=", value, "doctorUid");
            return (Criteria) this;
        }

        public Criteria andDoctorUidIn(List<Integer> values) {
            addCriterion("doctor_uid in", values, "doctorUid");
            return (Criteria) this;
        }

        public Criteria andDoctorUidNotIn(List<Integer> values) {
            addCriterion("doctor_uid not in", values, "doctorUid");
            return (Criteria) this;
        }

        public Criteria andDoctorUidBetween(Integer value1, Integer value2) {
            addCriterion("doctor_uid between", value1, value2, "doctorUid");
            return (Criteria) this;
        }

        public Criteria andDoctorUidNotBetween(Integer value1, Integer value2) {
            addCriterion("doctor_uid not between", value1, value2, "doctorUid");
            return (Criteria) this;
        }

        public Criteria andAppRoleUidIsNull() {
            addCriterion("app_role_uid is null");
            return (Criteria) this;
        }

        public Criteria andAppRoleUidIsNotNull() {
            addCriterion("app_role_uid is not null");
            return (Criteria) this;
        }

        public Criteria andAppRoleUidEqualTo(Integer value) {
            addCriterion("app_role_uid =", value, "appRoleUid");
            return (Criteria) this;
        }

        public Criteria andAppRoleUidNotEqualTo(Integer value) {
            addCriterion("app_role_uid <>", value, "appRoleUid");
            return (Criteria) this;
        }

        public Criteria andAppRoleUidGreaterThan(Integer value) {
            addCriterion("app_role_uid >", value, "appRoleUid");
            return (Criteria) this;
        }

        public Criteria andAppRoleUidGreaterThanOrEqualTo(Integer value) {
            addCriterion("app_role_uid >=", value, "appRoleUid");
            return (Criteria) this;
        }

        public Criteria andAppRoleUidLessThan(Integer value) {
            addCriterion("app_role_uid <", value, "appRoleUid");
            return (Criteria) this;
        }

        public Criteria andAppRoleUidLessThanOrEqualTo(Integer value) {
            addCriterion("app_role_uid <=", value, "appRoleUid");
            return (Criteria) this;
        }

        public Criteria andAppRoleUidIn(List<Integer> values) {
            addCriterion("app_role_uid in", values, "appRoleUid");
            return (Criteria) this;
        }

        public Criteria andAppRoleUidNotIn(List<Integer> values) {
            addCriterion("app_role_uid not in", values, "appRoleUid");
            return (Criteria) this;
        }

        public Criteria andAppRoleUidBetween(Integer value1, Integer value2) {
            addCriterion("app_role_uid between", value1, value2, "appRoleUid");
            return (Criteria) this;
        }

        public Criteria andAppRoleUidNotBetween(Integer value1, Integer value2) {
            addCriterion("app_role_uid not between", value1, value2, "appRoleUid");
            return (Criteria) this;
        }

        public Criteria andCreateTimeIsNull() {
            addCriterion("create_time is null");
            return (Criteria) this;
        }

        public Criteria andCreateTimeIsNotNull() {
            addCriterion("create_time is not null");
            return (Criteria) this;
        }

        public Criteria andCreateTimeEqualTo(Date value) {
            addCriterion("create_time =", value, "createTime");
            return (Criteria) this;
        }

        public Criteria andCreateTimeNotEqualTo(Date value) {
            addCriterion("create_time <>", value, "createTime");
            return (Criteria) this;
        }

        public Criteria andCreateTimeGreaterThan(Date value) {
            addCriterion("create_time >", value, "createTime");
            return (Criteria) this;
        }

        public Criteria andCreateTimeGreaterThanOrEqualTo(Date value) {
            addCriterion("create_time >=", value, "createTime");
            return (Criteria) this;
        }

        public Criteria andCreateTimeLessThan(Date value) {
            addCriterion("create_time <", value, "createTime");
            return (Criteria) this;
        }

        public Criteria andCreateTimeLessThanOrEqualTo(Date value) {
            addCriterion("create_time <=", value, "createTime");
            return (Criteria) this;
        }

        public Criteria andCreateTimeIn(List<Date> values) {
            addCriterion("create_time in", values, "createTime");
            return (Criteria) this;
        }

        public Criteria andCreateTimeNotIn(List<Date> values) {
            addCriterion("create_time not in", values, "createTime");
            return (Criteria) this;
        }

        public Criteria andCreateTimeBetween(Date value1, Date value2) {
            addCriterion("create_time between", value1, value2, "createTime");
            return (Criteria) this;
        }

        public Criteria andCreateTimeNotBetween(Date value1, Date value2) {
            addCriterion("create_time not between", value1, value2, "createTime");
            return (Criteria) this;
        }

        public Criteria andUpdateTimeIsNull() {
            addCriterion("update_time is null");
            return (Criteria) this;
        }

        public Criteria andUpdateTimeIsNotNull() {
            addCriterion("update_time is not null");
            return (Criteria) this;
        }

        public Criteria andUpdateTimeEqualTo(Date value) {
            addCriterion("update_time =", value, "updateTime");
            return (Criteria) this;
        }

        public Criteria andUpdateTimeNotEqualTo(Date value) {
            addCriterion("update_time <>", value, "updateTime");
            return (Criteria) this;
        }

        public Criteria andUpdateTimeGreaterThan(Date value) {
            addCriterion("update_time >", value, "updateTime");
            return (Criteria) this;
        }

        public Criteria andUpdateTimeGreaterThanOrEqualTo(Date value) {
            addCriterion("update_time >=", value, "updateTime");
            return (Criteria) this;
        }

        public Criteria andUpdateTimeLessThan(Date value) {
            addCriterion("update_time <", value, "updateTime");
            return (Criteria) this;
        }

        public Criteria andUpdateTimeLessThanOrEqualTo(Date value) {
            addCriterion("update_time <=", value, "updateTime");
            return (Criteria) this;
        }

        public Criteria andUpdateTimeIn(List<Date> values) {
            addCriterion("update_time in", values, "updateTime");
            return (Criteria) this;
        }

        public Criteria andUpdateTimeNotIn(List<Date> values) {
            addCriterion("update_time not in", values, "updateTime");
            return (Criteria) this;
        }

        public Criteria andUpdateTimeBetween(Date value1, Date value2) {
            addCriterion("update_time between", value1, value2, "updateTime");
            return (Criteria) this;
        }

        public Criteria andUpdateTimeNotBetween(Date value1, Date value2) {
            addCriterion("update_time not between", value1, value2, "updateTime");
            return (Criteria) this;
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table tb_doctor_app_role
     *
     * @mbggenerated do_not_delete_during_merge
     */
    public static class Criteria extends GeneratedCriteria {

        protected Criteria() {
            super();
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table tb_doctor_app_role
     *
     * @mbggenerated
     */
    public static class Criterion {
        private String condition;

        private Object value;

        private Object secondValue;

        private boolean noValue;

        private boolean singleValue;

        private boolean betweenValue;

        private boolean listValue;

        public String getCondition() {
            return condition;
        }

        public Object getValue() {
            return value;
        }

        public Object getSecondValue() {
            return secondValue;
        }

        public boolean isNoValue() {
            return noValue;
        }

        public boolean isSingleValue() {
            return singleValue;
        }

        public boolean isBetweenValue() {
            return betweenValue;
        }

        public boolean isListValue() {
            return listValue;
        }

        protected Criterion(String condition) {
            super();
            this.condition = condition;
            this.noValue = true;
        }

        protected Criterion(String condition, Object value) {
            super();
            this.condition = condition;
            this.value = value;
            if (value instanceof List<?>) {
                this.listValue = true;
            } else {
                this.singleValue = true;
            }
        }

        protected Criterion(String condition, Object value, Object secondValue) {
            super();
            this.condition = condition;
            this.value = value;
            this.secondValue = secondValue;
            this.betweenValue = true;
        }
    }
}