package org.zcgewu.study.soa.doctor.po;

import java.util.ArrayList;
import java.util.Date;
import java.util.List;

public class DoctorExample {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table tb_doctor
     *
     * @mbggenerated
     */
    protected String orderByClause;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table tb_doctor
     *
     * @mbggenerated
     */
    protected boolean distinct;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table tb_doctor
     *
     * @mbggenerated
     */
    protected List<Criteria> oredCriteria;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table tb_doctor
     *
     * @mbggenerated
     */
    protected Integer limitStart;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table tb_doctor
     *
     * @mbggenerated
     */
    protected Integer limitEnd;

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_doctor
     *
     * @mbggenerated
     */
    public DoctorExample() {
        oredCriteria = new ArrayList<Criteria>();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_doctor
     *
     * @mbggenerated
     */
    public void setOrderByClause(String orderByClause) {
        this.orderByClause = orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_doctor
     *
     * @mbggenerated
     */
    public String getOrderByClause() {
        return orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_doctor
     *
     * @mbggenerated
     */
    public void setDistinct(boolean distinct) {
        this.distinct = distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_doctor
     *
     * @mbggenerated
     */
    public boolean isDistinct() {
        return distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_doctor
     *
     * @mbggenerated
     */
    public List<Criteria> getOredCriteria() {
        return oredCriteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_doctor
     *
     * @mbggenerated
     */
    public void or(Criteria criteria) {
        oredCriteria.add(criteria);
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_doctor
     *
     * @mbggenerated
     */
    public Criteria or() {
        Criteria criteria = createCriteriaInternal();
        oredCriteria.add(criteria);
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_doctor
     *
     * @mbggenerated
     */
    public Criteria createCriteria() {
        Criteria criteria = createCriteriaInternal();
        if (oredCriteria.size() == 0) {
            oredCriteria.add(criteria);
        }
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_doctor
     *
     * @mbggenerated
     */
    protected Criteria createCriteriaInternal() {
        Criteria criteria = new Criteria();
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_doctor
     *
     * @mbggenerated
     */
    public void clear() {
        oredCriteria.clear();
        orderByClause = null;
        distinct = false;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_doctor
     *
     * @mbggenerated
     */
    public void setLimitStart(Integer limitStart) {
        this.limitStart=limitStart;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_doctor
     *
     * @mbggenerated
     */
    public Integer getLimitStart() {
        return limitStart;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_doctor
     *
     * @mbggenerated
     */
    public void setLimitEnd(Integer limitEnd) {
        this.limitEnd=limitEnd;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_doctor
     *
     * @mbggenerated
     */
    public Integer getLimitEnd() {
        return limitEnd;
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table tb_doctor
     *
     * @mbggenerated
     */
    protected abstract static class GeneratedCriteria {
        protected List<Criterion> criteria;

        protected GeneratedCriteria() {
            super();
            criteria = new ArrayList<Criterion>();
        }

        public boolean isValid() {
            return criteria.size() > 0;
        }

        public List<Criterion> getCriteria() {
            return criteria;
        }

        protected void addCriterion(String condition) {
            if (condition == null) {
                throw new RuntimeException("Value for condition cannot be null");
            }
            criteria.add(new Criterion(condition));
        }

        protected void addCriterion(String condition, Object value, String property) {
            if (value == null) {
                throw new RuntimeException("Value for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value));
        }

        protected void addCriterion(String condition, Object value1, Object value2, String property) {
            if (value1 == null || value2 == null) {
                throw new RuntimeException("Between values for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value1, value2));
        }

        public Criteria andDoctorUIDIsNull() {
            addCriterion("DoctorUID is null");
            return (Criteria) this;
        }

        public Criteria andDoctorUIDIsNotNull() {
            addCriterion("DoctorUID is not null");
            return (Criteria) this;
        }

        public Criteria andDoctorUIDEqualTo(Integer value) {
            addCriterion("DoctorUID =", value, "doctorUID");
            return (Criteria) this;
        }

        public Criteria andDoctorUIDNotEqualTo(Integer value) {
            addCriterion("DoctorUID <>", value, "doctorUID");
            return (Criteria) this;
        }

        public Criteria andDoctorUIDGreaterThan(Integer value) {
            addCriterion("DoctorUID >", value, "doctorUID");
            return (Criteria) this;
        }

        public Criteria andDoctorUIDGreaterThanOrEqualTo(Integer value) {
            addCriterion("DoctorUID >=", value, "doctorUID");
            return (Criteria) this;
        }

        public Criteria andDoctorUIDLessThan(Integer value) {
            addCriterion("DoctorUID <", value, "doctorUID");
            return (Criteria) this;
        }

        public Criteria andDoctorUIDLessThanOrEqualTo(Integer value) {
            addCriterion("DoctorUID <=", value, "doctorUID");
            return (Criteria) this;
        }

        public Criteria andDoctorUIDIn(List<Integer> values) {
            addCriterion("DoctorUID in", values, "doctorUID");
            return (Criteria) this;
        }

        public Criteria andDoctorUIDNotIn(List<Integer> values) {
            addCriterion("DoctorUID not in", values, "doctorUID");
            return (Criteria) this;
        }

        public Criteria andDoctorUIDBetween(Integer value1, Integer value2) {
            addCriterion("DoctorUID between", value1, value2, "doctorUID");
            return (Criteria) this;
        }

        public Criteria andDoctorUIDNotBetween(Integer value1, Integer value2) {
            addCriterion("DoctorUID not between", value1, value2, "doctorUID");
            return (Criteria) this;
        }

        public Criteria andHospitalUIDIsNull() {
            addCriterion("HospitalUID is null");
            return (Criteria) this;
        }

        public Criteria andHospitalUIDIsNotNull() {
            addCriterion("HospitalUID is not null");
            return (Criteria) this;
        }

        public Criteria andHospitalUIDEqualTo(Integer value) {
            addCriterion("HospitalUID =", value, "hospitalUID");
            return (Criteria) this;
        }

        public Criteria andHospitalUIDNotEqualTo(Integer value) {
            addCriterion("HospitalUID <>", value, "hospitalUID");
            return (Criteria) this;
        }

        public Criteria andHospitalUIDGreaterThan(Integer value) {
            addCriterion("HospitalUID >", value, "hospitalUID");
            return (Criteria) this;
        }

        public Criteria andHospitalUIDGreaterThanOrEqualTo(Integer value) {
            addCriterion("HospitalUID >=", value, "hospitalUID");
            return (Criteria) this;
        }

        public Criteria andHospitalUIDLessThan(Integer value) {
            addCriterion("HospitalUID <", value, "hospitalUID");
            return (Criteria) this;
        }

        public Criteria andHospitalUIDLessThanOrEqualTo(Integer value) {
            addCriterion("HospitalUID <=", value, "hospitalUID");
            return (Criteria) this;
        }

        public Criteria andHospitalUIDIn(List<Integer> values) {
            addCriterion("HospitalUID in", values, "hospitalUID");
            return (Criteria) this;
        }

        public Criteria andHospitalUIDNotIn(List<Integer> values) {
            addCriterion("HospitalUID not in", values, "hospitalUID");
            return (Criteria) this;
        }

        public Criteria andHospitalUIDBetween(Integer value1, Integer value2) {
            addCriterion("HospitalUID between", value1, value2, "hospitalUID");
            return (Criteria) this;
        }

        public Criteria andHospitalUIDNotBetween(Integer value1, Integer value2) {
            addCriterion("HospitalUID not between", value1, value2, "hospitalUID");
            return (Criteria) this;
        }

        public Criteria andRtisDoctorUIDIsNull() {
            addCriterion("RtisDoctorUID is null");
            return (Criteria) this;
        }

        public Criteria andRtisDoctorUIDIsNotNull() {
            addCriterion("RtisDoctorUID is not null");
            return (Criteria) this;
        }

        public Criteria andRtisDoctorUIDEqualTo(String value) {
            addCriterion("RtisDoctorUID =", value, "rtisDoctorUID");
            return (Criteria) this;
        }

        public Criteria andRtisDoctorUIDNotEqualTo(String value) {
            addCriterion("RtisDoctorUID <>", value, "rtisDoctorUID");
            return (Criteria) this;
        }

        public Criteria andRtisDoctorUIDGreaterThan(String value) {
            addCriterion("RtisDoctorUID >", value, "rtisDoctorUID");
            return (Criteria) this;
        }

        public Criteria andRtisDoctorUIDGreaterThanOrEqualTo(String value) {
            addCriterion("RtisDoctorUID >=", value, "rtisDoctorUID");
            return (Criteria) this;
        }

        public Criteria andRtisDoctorUIDLessThan(String value) {
            addCriterion("RtisDoctorUID <", value, "rtisDoctorUID");
            return (Criteria) this;
        }

        public Criteria andRtisDoctorUIDLessThanOrEqualTo(String value) {
            addCriterion("RtisDoctorUID <=", value, "rtisDoctorUID");
            return (Criteria) this;
        }

        public Criteria andRtisDoctorUIDLike(String value) {
            addCriterion("RtisDoctorUID like", value, "rtisDoctorUID");
            return (Criteria) this;
        }

        public Criteria andRtisDoctorUIDNotLike(String value) {
            addCriterion("RtisDoctorUID not like", value, "rtisDoctorUID");
            return (Criteria) this;
        }

        public Criteria andRtisDoctorUIDIn(List<String> values) {
            addCriterion("RtisDoctorUID in", values, "rtisDoctorUID");
            return (Criteria) this;
        }

        public Criteria andRtisDoctorUIDNotIn(List<String> values) {
            addCriterion("RtisDoctorUID not in", values, "rtisDoctorUID");
            return (Criteria) this;
        }

        public Criteria andRtisDoctorUIDBetween(String value1, String value2) {
            addCriterion("RtisDoctorUID between", value1, value2, "rtisDoctorUID");
            return (Criteria) this;
        }

        public Criteria andRtisDoctorUIDNotBetween(String value1, String value2) {
            addCriterion("RtisDoctorUID not between", value1, value2, "rtisDoctorUID");
            return (Criteria) this;
        }

        public Criteria andPasswordIsNull() {
            addCriterion("Password is null");
            return (Criteria) this;
        }

        public Criteria andPasswordIsNotNull() {
            addCriterion("Password is not null");
            return (Criteria) this;
        }

        public Criteria andPasswordEqualTo(String value) {
            addCriterion("Password =", value, "password");
            return (Criteria) this;
        }

        public Criteria andPasswordNotEqualTo(String value) {
            addCriterion("Password <>", value, "password");
            return (Criteria) this;
        }

        public Criteria andPasswordGreaterThan(String value) {
            addCriterion("Password >", value, "password");
            return (Criteria) this;
        }

        public Criteria andPasswordGreaterThanOrEqualTo(String value) {
            addCriterion("Password >=", value, "password");
            return (Criteria) this;
        }

        public Criteria andPasswordLessThan(String value) {
            addCriterion("Password <", value, "password");
            return (Criteria) this;
        }

        public Criteria andPasswordLessThanOrEqualTo(String value) {
            addCriterion("Password <=", value, "password");
            return (Criteria) this;
        }

        public Criteria andPasswordLike(String value) {
            addCriterion("Password like", value, "password");
            return (Criteria) this;
        }

        public Criteria andPasswordNotLike(String value) {
            addCriterion("Password not like", value, "password");
            return (Criteria) this;
        }

        public Criteria andPasswordIn(List<String> values) {
            addCriterion("Password in", values, "password");
            return (Criteria) this;
        }

        public Criteria andPasswordNotIn(List<String> values) {
            addCriterion("Password not in", values, "password");
            return (Criteria) this;
        }

        public Criteria andPasswordBetween(String value1, String value2) {
            addCriterion("Password between", value1, value2, "password");
            return (Criteria) this;
        }

        public Criteria andPasswordNotBetween(String value1, String value2) {
            addCriterion("Password not between", value1, value2, "password");
            return (Criteria) this;
        }

        public Criteria andDoctorNameIsNull() {
            addCriterion("DoctorName is null");
            return (Criteria) this;
        }

        public Criteria andDoctorNameIsNotNull() {
            addCriterion("DoctorName is not null");
            return (Criteria) this;
        }

        public Criteria andDoctorNameEqualTo(String value) {
            addCriterion("DoctorName =", value, "doctorName");
            return (Criteria) this;
        }

        public Criteria andDoctorNameNotEqualTo(String value) {
            addCriterion("DoctorName <>", value, "doctorName");
            return (Criteria) this;
        }

        public Criteria andDoctorNameGreaterThan(String value) {
            addCriterion("DoctorName >", value, "doctorName");
            return (Criteria) this;
        }

        public Criteria andDoctorNameGreaterThanOrEqualTo(String value) {
            addCriterion("DoctorName >=", value, "doctorName");
            return (Criteria) this;
        }

        public Criteria andDoctorNameLessThan(String value) {
            addCriterion("DoctorName <", value, "doctorName");
            return (Criteria) this;
        }

        public Criteria andDoctorNameLessThanOrEqualTo(String value) {
            addCriterion("DoctorName <=", value, "doctorName");
            return (Criteria) this;
        }

        public Criteria andDoctorNameLike(String value) {
            addCriterion("DoctorName like", value, "doctorName");
            return (Criteria) this;
        }

        public Criteria andDoctorNameNotLike(String value) {
            addCriterion("DoctorName not like", value, "doctorName");
            return (Criteria) this;
        }

        public Criteria andDoctorNameIn(List<String> values) {
            addCriterion("DoctorName in", values, "doctorName");
            return (Criteria) this;
        }

        public Criteria andDoctorNameNotIn(List<String> values) {
            addCriterion("DoctorName not in", values, "doctorName");
            return (Criteria) this;
        }

        public Criteria andDoctorNameBetween(String value1, String value2) {
            addCriterion("DoctorName between", value1, value2, "doctorName");
            return (Criteria) this;
        }

        public Criteria andDoctorNameNotBetween(String value1, String value2) {
            addCriterion("DoctorName not between", value1, value2, "doctorName");
            return (Criteria) this;
        }

        public Criteria andAppCellPhoneIsNull() {
            addCriterion("AppCellPhone is null");
            return (Criteria) this;
        }

        public Criteria andAppCellPhoneIsNotNull() {
            addCriterion("AppCellPhone is not null");
            return (Criteria) this;
        }

        public Criteria andAppCellPhoneEqualTo(String value) {
            addCriterion("AppCellPhone =", value, "appCellPhone");
            return (Criteria) this;
        }

        public Criteria andAppCellPhoneNotEqualTo(String value) {
            addCriterion("AppCellPhone <>", value, "appCellPhone");
            return (Criteria) this;
        }

        public Criteria andAppCellPhoneGreaterThan(String value) {
            addCriterion("AppCellPhone >", value, "appCellPhone");
            return (Criteria) this;
        }

        public Criteria andAppCellPhoneGreaterThanOrEqualTo(String value) {
            addCriterion("AppCellPhone >=", value, "appCellPhone");
            return (Criteria) this;
        }

        public Criteria andAppCellPhoneLessThan(String value) {
            addCriterion("AppCellPhone <", value, "appCellPhone");
            return (Criteria) this;
        }

        public Criteria andAppCellPhoneLessThanOrEqualTo(String value) {
            addCriterion("AppCellPhone <=", value, "appCellPhone");
            return (Criteria) this;
        }

        public Criteria andAppCellPhoneLike(String value) {
            addCriterion("AppCellPhone like", value, "appCellPhone");
            return (Criteria) this;
        }

        public Criteria andAppCellPhoneNotLike(String value) {
            addCriterion("AppCellPhone not like", value, "appCellPhone");
            return (Criteria) this;
        }

        public Criteria andAppCellPhoneIn(List<String> values) {
            addCriterion("AppCellPhone in", values, "appCellPhone");
            return (Criteria) this;
        }

        public Criteria andAppCellPhoneNotIn(List<String> values) {
            addCriterion("AppCellPhone not in", values, "appCellPhone");
            return (Criteria) this;
        }

        public Criteria andAppCellPhoneBetween(String value1, String value2) {
            addCriterion("AppCellPhone between", value1, value2, "appCellPhone");
            return (Criteria) this;
        }

        public Criteria andAppCellPhoneNotBetween(String value1, String value2) {
            addCriterion("AppCellPhone not between", value1, value2, "appCellPhone");
            return (Criteria) this;
        }

        public Criteria andCellPhoneIsNull() {
            addCriterion("CellPhone is null");
            return (Criteria) this;
        }

        public Criteria andCellPhoneIsNotNull() {
            addCriterion("CellPhone is not null");
            return (Criteria) this;
        }

        public Criteria andCellPhoneEqualTo(String value) {
            addCriterion("CellPhone =", value, "cellPhone");
            return (Criteria) this;
        }

        public Criteria andCellPhoneNotEqualTo(String value) {
            addCriterion("CellPhone <>", value, "cellPhone");
            return (Criteria) this;
        }

        public Criteria andCellPhoneGreaterThan(String value) {
            addCriterion("CellPhone >", value, "cellPhone");
            return (Criteria) this;
        }

        public Criteria andCellPhoneGreaterThanOrEqualTo(String value) {
            addCriterion("CellPhone >=", value, "cellPhone");
            return (Criteria) this;
        }

        public Criteria andCellPhoneLessThan(String value) {
            addCriterion("CellPhone <", value, "cellPhone");
            return (Criteria) this;
        }

        public Criteria andCellPhoneLessThanOrEqualTo(String value) {
            addCriterion("CellPhone <=", value, "cellPhone");
            return (Criteria) this;
        }

        public Criteria andCellPhoneLike(String value) {
            addCriterion("CellPhone like", value, "cellPhone");
            return (Criteria) this;
        }

        public Criteria andCellPhoneNotLike(String value) {
            addCriterion("CellPhone not like", value, "cellPhone");
            return (Criteria) this;
        }

        public Criteria andCellPhoneIn(List<String> values) {
            addCriterion("CellPhone in", values, "cellPhone");
            return (Criteria) this;
        }

        public Criteria andCellPhoneNotIn(List<String> values) {
            addCriterion("CellPhone not in", values, "cellPhone");
            return (Criteria) this;
        }

        public Criteria andCellPhoneBetween(String value1, String value2) {
            addCriterion("CellPhone between", value1, value2, "cellPhone");
            return (Criteria) this;
        }

        public Criteria andCellPhoneNotBetween(String value1, String value2) {
            addCriterion("CellPhone not between", value1, value2, "cellPhone");
            return (Criteria) this;
        }

        public Criteria andNativePlaceIsNull() {
            addCriterion("NativePlace is null");
            return (Criteria) this;
        }

        public Criteria andNativePlaceIsNotNull() {
            addCriterion("NativePlace is not null");
            return (Criteria) this;
        }

        public Criteria andNativePlaceEqualTo(String value) {
            addCriterion("NativePlace =", value, "nativePlace");
            return (Criteria) this;
        }

        public Criteria andNativePlaceNotEqualTo(String value) {
            addCriterion("NativePlace <>", value, "nativePlace");
            return (Criteria) this;
        }

        public Criteria andNativePlaceGreaterThan(String value) {
            addCriterion("NativePlace >", value, "nativePlace");
            return (Criteria) this;
        }

        public Criteria andNativePlaceGreaterThanOrEqualTo(String value) {
            addCriterion("NativePlace >=", value, "nativePlace");
            return (Criteria) this;
        }

        public Criteria andNativePlaceLessThan(String value) {
            addCriterion("NativePlace <", value, "nativePlace");
            return (Criteria) this;
        }

        public Criteria andNativePlaceLessThanOrEqualTo(String value) {
            addCriterion("NativePlace <=", value, "nativePlace");
            return (Criteria) this;
        }

        public Criteria andNativePlaceLike(String value) {
            addCriterion("NativePlace like", value, "nativePlace");
            return (Criteria) this;
        }

        public Criteria andNativePlaceNotLike(String value) {
            addCriterion("NativePlace not like", value, "nativePlace");
            return (Criteria) this;
        }

        public Criteria andNativePlaceIn(List<String> values) {
            addCriterion("NativePlace in", values, "nativePlace");
            return (Criteria) this;
        }

        public Criteria andNativePlaceNotIn(List<String> values) {
            addCriterion("NativePlace not in", values, "nativePlace");
            return (Criteria) this;
        }

        public Criteria andNativePlaceBetween(String value1, String value2) {
            addCriterion("NativePlace between", value1, value2, "nativePlace");
            return (Criteria) this;
        }

        public Criteria andNativePlaceNotBetween(String value1, String value2) {
            addCriterion("NativePlace not between", value1, value2, "nativePlace");
            return (Criteria) this;
        }

        public Criteria andBirthdayIsNull() {
            addCriterion("Birthday is null");
            return (Criteria) this;
        }

        public Criteria andBirthdayIsNotNull() {
            addCriterion("Birthday is not null");
            return (Criteria) this;
        }

        public Criteria andBirthdayEqualTo(Date value) {
            addCriterion("Birthday =", value, "birthday");
            return (Criteria) this;
        }

        public Criteria andBirthdayNotEqualTo(Date value) {
            addCriterion("Birthday <>", value, "birthday");
            return (Criteria) this;
        }

        public Criteria andBirthdayGreaterThan(Date value) {
            addCriterion("Birthday >", value, "birthday");
            return (Criteria) this;
        }

        public Criteria andBirthdayGreaterThanOrEqualTo(Date value) {
            addCriterion("Birthday >=", value, "birthday");
            return (Criteria) this;
        }

        public Criteria andBirthdayLessThan(Date value) {
            addCriterion("Birthday <", value, "birthday");
            return (Criteria) this;
        }

        public Criteria andBirthdayLessThanOrEqualTo(Date value) {
            addCriterion("Birthday <=", value, "birthday");
            return (Criteria) this;
        }

        public Criteria andBirthdayIn(List<Date> values) {
            addCriterion("Birthday in", values, "birthday");
            return (Criteria) this;
        }

        public Criteria andBirthdayNotIn(List<Date> values) {
            addCriterion("Birthday not in", values, "birthday");
            return (Criteria) this;
        }

        public Criteria andBirthdayBetween(Date value1, Date value2) {
            addCriterion("Birthday between", value1, value2, "birthday");
            return (Criteria) this;
        }

        public Criteria andBirthdayNotBetween(Date value1, Date value2) {
            addCriterion("Birthday not between", value1, value2, "birthday");
            return (Criteria) this;
        }

        public Criteria andNationalityIsNull() {
            addCriterion("Nationality is null");
            return (Criteria) this;
        }

        public Criteria andNationalityIsNotNull() {
            addCriterion("Nationality is not null");
            return (Criteria) this;
        }

        public Criteria andNationalityEqualTo(String value) {
            addCriterion("Nationality =", value, "nationality");
            return (Criteria) this;
        }

        public Criteria andNationalityNotEqualTo(String value) {
            addCriterion("Nationality <>", value, "nationality");
            return (Criteria) this;
        }

        public Criteria andNationalityGreaterThan(String value) {
            addCriterion("Nationality >", value, "nationality");
            return (Criteria) this;
        }

        public Criteria andNationalityGreaterThanOrEqualTo(String value) {
            addCriterion("Nationality >=", value, "nationality");
            return (Criteria) this;
        }

        public Criteria andNationalityLessThan(String value) {
            addCriterion("Nationality <", value, "nationality");
            return (Criteria) this;
        }

        public Criteria andNationalityLessThanOrEqualTo(String value) {
            addCriterion("Nationality <=", value, "nationality");
            return (Criteria) this;
        }

        public Criteria andNationalityLike(String value) {
            addCriterion("Nationality like", value, "nationality");
            return (Criteria) this;
        }

        public Criteria andNationalityNotLike(String value) {
            addCriterion("Nationality not like", value, "nationality");
            return (Criteria) this;
        }

        public Criteria andNationalityIn(List<String> values) {
            addCriterion("Nationality in", values, "nationality");
            return (Criteria) this;
        }

        public Criteria andNationalityNotIn(List<String> values) {
            addCriterion("Nationality not in", values, "nationality");
            return (Criteria) this;
        }

        public Criteria andNationalityBetween(String value1, String value2) {
            addCriterion("Nationality between", value1, value2, "nationality");
            return (Criteria) this;
        }

        public Criteria andNationalityNotBetween(String value1, String value2) {
            addCriterion("Nationality not between", value1, value2, "nationality");
            return (Criteria) this;
        }

        public Criteria andStationaryPhoneIsNull() {
            addCriterion("StationaryPhone is null");
            return (Criteria) this;
        }

        public Criteria andStationaryPhoneIsNotNull() {
            addCriterion("StationaryPhone is not null");
            return (Criteria) this;
        }

        public Criteria andStationaryPhoneEqualTo(String value) {
            addCriterion("StationaryPhone =", value, "stationaryPhone");
            return (Criteria) this;
        }

        public Criteria andStationaryPhoneNotEqualTo(String value) {
            addCriterion("StationaryPhone <>", value, "stationaryPhone");
            return (Criteria) this;
        }

        public Criteria andStationaryPhoneGreaterThan(String value) {
            addCriterion("StationaryPhone >", value, "stationaryPhone");
            return (Criteria) this;
        }

        public Criteria andStationaryPhoneGreaterThanOrEqualTo(String value) {
            addCriterion("StationaryPhone >=", value, "stationaryPhone");
            return (Criteria) this;
        }

        public Criteria andStationaryPhoneLessThan(String value) {
            addCriterion("StationaryPhone <", value, "stationaryPhone");
            return (Criteria) this;
        }

        public Criteria andStationaryPhoneLessThanOrEqualTo(String value) {
            addCriterion("StationaryPhone <=", value, "stationaryPhone");
            return (Criteria) this;
        }

        public Criteria andStationaryPhoneLike(String value) {
            addCriterion("StationaryPhone like", value, "stationaryPhone");
            return (Criteria) this;
        }

        public Criteria andStationaryPhoneNotLike(String value) {
            addCriterion("StationaryPhone not like", value, "stationaryPhone");
            return (Criteria) this;
        }

        public Criteria andStationaryPhoneIn(List<String> values) {
            addCriterion("StationaryPhone in", values, "stationaryPhone");
            return (Criteria) this;
        }

        public Criteria andStationaryPhoneNotIn(List<String> values) {
            addCriterion("StationaryPhone not in", values, "stationaryPhone");
            return (Criteria) this;
        }

        public Criteria andStationaryPhoneBetween(String value1, String value2) {
            addCriterion("StationaryPhone between", value1, value2, "stationaryPhone");
            return (Criteria) this;
        }

        public Criteria andStationaryPhoneNotBetween(String value1, String value2) {
            addCriterion("StationaryPhone not between", value1, value2, "stationaryPhone");
            return (Criteria) this;
        }

        public Criteria andAddressIsNull() {
            addCriterion("Address is null");
            return (Criteria) this;
        }

        public Criteria andAddressIsNotNull() {
            addCriterion("Address is not null");
            return (Criteria) this;
        }

        public Criteria andAddressEqualTo(String value) {
            addCriterion("Address =", value, "address");
            return (Criteria) this;
        }

        public Criteria andAddressNotEqualTo(String value) {
            addCriterion("Address <>", value, "address");
            return (Criteria) this;
        }

        public Criteria andAddressGreaterThan(String value) {
            addCriterion("Address >", value, "address");
            return (Criteria) this;
        }

        public Criteria andAddressGreaterThanOrEqualTo(String value) {
            addCriterion("Address >=", value, "address");
            return (Criteria) this;
        }

        public Criteria andAddressLessThan(String value) {
            addCriterion("Address <", value, "address");
            return (Criteria) this;
        }

        public Criteria andAddressLessThanOrEqualTo(String value) {
            addCriterion("Address <=", value, "address");
            return (Criteria) this;
        }

        public Criteria andAddressLike(String value) {
            addCriterion("Address like", value, "address");
            return (Criteria) this;
        }

        public Criteria andAddressNotLike(String value) {
            addCriterion("Address not like", value, "address");
            return (Criteria) this;
        }

        public Criteria andAddressIn(List<String> values) {
            addCriterion("Address in", values, "address");
            return (Criteria) this;
        }

        public Criteria andAddressNotIn(List<String> values) {
            addCriterion("Address not in", values, "address");
            return (Criteria) this;
        }

        public Criteria andAddressBetween(String value1, String value2) {
            addCriterion("Address between", value1, value2, "address");
            return (Criteria) this;
        }

        public Criteria andAddressNotBetween(String value1, String value2) {
            addCriterion("Address not between", value1, value2, "address");
            return (Criteria) this;
        }

        public Criteria andPicturlURLIsNull() {
            addCriterion("PicturlURL is null");
            return (Criteria) this;
        }

        public Criteria andPicturlURLIsNotNull() {
            addCriterion("PicturlURL is not null");
            return (Criteria) this;
        }

        public Criteria andPicturlURLEqualTo(String value) {
            addCriterion("PicturlURL =", value, "picturlURL");
            return (Criteria) this;
        }

        public Criteria andPicturlURLNotEqualTo(String value) {
            addCriterion("PicturlURL <>", value, "picturlURL");
            return (Criteria) this;
        }

        public Criteria andPicturlURLGreaterThan(String value) {
            addCriterion("PicturlURL >", value, "picturlURL");
            return (Criteria) this;
        }

        public Criteria andPicturlURLGreaterThanOrEqualTo(String value) {
            addCriterion("PicturlURL >=", value, "picturlURL");
            return (Criteria) this;
        }

        public Criteria andPicturlURLLessThan(String value) {
            addCriterion("PicturlURL <", value, "picturlURL");
            return (Criteria) this;
        }

        public Criteria andPicturlURLLessThanOrEqualTo(String value) {
            addCriterion("PicturlURL <=", value, "picturlURL");
            return (Criteria) this;
        }

        public Criteria andPicturlURLLike(String value) {
            addCriterion("PicturlURL like", value, "picturlURL");
            return (Criteria) this;
        }

        public Criteria andPicturlURLNotLike(String value) {
            addCriterion("PicturlURL not like", value, "picturlURL");
            return (Criteria) this;
        }

        public Criteria andPicturlURLIn(List<String> values) {
            addCriterion("PicturlURL in", values, "picturlURL");
            return (Criteria) this;
        }

        public Criteria andPicturlURLNotIn(List<String> values) {
            addCriterion("PicturlURL not in", values, "picturlURL");
            return (Criteria) this;
        }

        public Criteria andPicturlURLBetween(String value1, String value2) {
            addCriterion("PicturlURL between", value1, value2, "picturlURL");
            return (Criteria) this;
        }

        public Criteria andPicturlURLNotBetween(String value1, String value2) {
            addCriterion("PicturlURL not between", value1, value2, "picturlURL");
            return (Criteria) this;
        }

        public Criteria andAgeIsNull() {
            addCriterion("Age is null");
            return (Criteria) this;
        }

        public Criteria andAgeIsNotNull() {
            addCriterion("Age is not null");
            return (Criteria) this;
        }

        public Criteria andAgeEqualTo(Short value) {
            addCriterion("Age =", value, "age");
            return (Criteria) this;
        }

        public Criteria andAgeNotEqualTo(Short value) {
            addCriterion("Age <>", value, "age");
            return (Criteria) this;
        }

        public Criteria andAgeGreaterThan(Short value) {
            addCriterion("Age >", value, "age");
            return (Criteria) this;
        }

        public Criteria andAgeGreaterThanOrEqualTo(Short value) {
            addCriterion("Age >=", value, "age");
            return (Criteria) this;
        }

        public Criteria andAgeLessThan(Short value) {
            addCriterion("Age <", value, "age");
            return (Criteria) this;
        }

        public Criteria andAgeLessThanOrEqualTo(Short value) {
            addCriterion("Age <=", value, "age");
            return (Criteria) this;
        }

        public Criteria andAgeIn(List<Short> values) {
            addCriterion("Age in", values, "age");
            return (Criteria) this;
        }

        public Criteria andAgeNotIn(List<Short> values) {
            addCriterion("Age not in", values, "age");
            return (Criteria) this;
        }

        public Criteria andAgeBetween(Short value1, Short value2) {
            addCriterion("Age between", value1, value2, "age");
            return (Criteria) this;
        }

        public Criteria andAgeNotBetween(Short value1, Short value2) {
            addCriterion("Age not between", value1, value2, "age");
            return (Criteria) this;
        }

        public Criteria andSexIsNull() {
            addCriterion("Sex is null");
            return (Criteria) this;
        }

        public Criteria andSexIsNotNull() {
            addCriterion("Sex is not null");
            return (Criteria) this;
        }

        public Criteria andSexEqualTo(String value) {
            addCriterion("Sex =", value, "sex");
            return (Criteria) this;
        }

        public Criteria andSexNotEqualTo(String value) {
            addCriterion("Sex <>", value, "sex");
            return (Criteria) this;
        }

        public Criteria andSexGreaterThan(String value) {
            addCriterion("Sex >", value, "sex");
            return (Criteria) this;
        }

        public Criteria andSexGreaterThanOrEqualTo(String value) {
            addCriterion("Sex >=", value, "sex");
            return (Criteria) this;
        }

        public Criteria andSexLessThan(String value) {
            addCriterion("Sex <", value, "sex");
            return (Criteria) this;
        }

        public Criteria andSexLessThanOrEqualTo(String value) {
            addCriterion("Sex <=", value, "sex");
            return (Criteria) this;
        }

        public Criteria andSexLike(String value) {
            addCriterion("Sex like", value, "sex");
            return (Criteria) this;
        }

        public Criteria andSexNotLike(String value) {
            addCriterion("Sex not like", value, "sex");
            return (Criteria) this;
        }

        public Criteria andSexIn(List<String> values) {
            addCriterion("Sex in", values, "sex");
            return (Criteria) this;
        }

        public Criteria andSexNotIn(List<String> values) {
            addCriterion("Sex not in", values, "sex");
            return (Criteria) this;
        }

        public Criteria andSexBetween(String value1, String value2) {
            addCriterion("Sex between", value1, value2, "sex");
            return (Criteria) this;
        }

        public Criteria andSexNotBetween(String value1, String value2) {
            addCriterion("Sex not between", value1, value2, "sex");
            return (Criteria) this;
        }

        public Criteria andIDNumberIsNull() {
            addCriterion("IDNumber is null");
            return (Criteria) this;
        }

        public Criteria andIDNumberIsNotNull() {
            addCriterion("IDNumber is not null");
            return (Criteria) this;
        }

        public Criteria andIDNumberEqualTo(String value) {
            addCriterion("IDNumber =", value, "IDNumber");
            return (Criteria) this;
        }

        public Criteria andIDNumberNotEqualTo(String value) {
            addCriterion("IDNumber <>", value, "IDNumber");
            return (Criteria) this;
        }

        public Criteria andIDNumberGreaterThan(String value) {
            addCriterion("IDNumber >", value, "IDNumber");
            return (Criteria) this;
        }

        public Criteria andIDNumberGreaterThanOrEqualTo(String value) {
            addCriterion("IDNumber >=", value, "IDNumber");
            return (Criteria) this;
        }

        public Criteria andIDNumberLessThan(String value) {
            addCriterion("IDNumber <", value, "IDNumber");
            return (Criteria) this;
        }

        public Criteria andIDNumberLessThanOrEqualTo(String value) {
            addCriterion("IDNumber <=", value, "IDNumber");
            return (Criteria) this;
        }

        public Criteria andIDNumberLike(String value) {
            addCriterion("IDNumber like", value, "IDNumber");
            return (Criteria) this;
        }

        public Criteria andIDNumberNotLike(String value) {
            addCriterion("IDNumber not like", value, "IDNumber");
            return (Criteria) this;
        }

        public Criteria andIDNumberIn(List<String> values) {
            addCriterion("IDNumber in", values, "IDNumber");
            return (Criteria) this;
        }

        public Criteria andIDNumberNotIn(List<String> values) {
            addCriterion("IDNumber not in", values, "IDNumber");
            return (Criteria) this;
        }

        public Criteria andIDNumberBetween(String value1, String value2) {
            addCriterion("IDNumber between", value1, value2, "IDNumber");
            return (Criteria) this;
        }

        public Criteria andIDNumberNotBetween(String value1, String value2) {
            addCriterion("IDNumber not between", value1, value2, "IDNumber");
            return (Criteria) this;
        }

        public Criteria andTechnicalPostUIDIsNull() {
            addCriterion("TechnicalPostUID is null");
            return (Criteria) this;
        }

        public Criteria andTechnicalPostUIDIsNotNull() {
            addCriterion("TechnicalPostUID is not null");
            return (Criteria) this;
        }

        public Criteria andTechnicalPostUIDEqualTo(Integer value) {
            addCriterion("TechnicalPostUID =", value, "technicalPostUID");
            return (Criteria) this;
        }

        public Criteria andTechnicalPostUIDNotEqualTo(Integer value) {
            addCriterion("TechnicalPostUID <>", value, "technicalPostUID");
            return (Criteria) this;
        }

        public Criteria andTechnicalPostUIDGreaterThan(Integer value) {
            addCriterion("TechnicalPostUID >", value, "technicalPostUID");
            return (Criteria) this;
        }

        public Criteria andTechnicalPostUIDGreaterThanOrEqualTo(Integer value) {
            addCriterion("TechnicalPostUID >=", value, "technicalPostUID");
            return (Criteria) this;
        }

        public Criteria andTechnicalPostUIDLessThan(Integer value) {
            addCriterion("TechnicalPostUID <", value, "technicalPostUID");
            return (Criteria) this;
        }

        public Criteria andTechnicalPostUIDLessThanOrEqualTo(Integer value) {
            addCriterion("TechnicalPostUID <=", value, "technicalPostUID");
            return (Criteria) this;
        }

        public Criteria andTechnicalPostUIDIn(List<Integer> values) {
            addCriterion("TechnicalPostUID in", values, "technicalPostUID");
            return (Criteria) this;
        }

        public Criteria andTechnicalPostUIDNotIn(List<Integer> values) {
            addCriterion("TechnicalPostUID not in", values, "technicalPostUID");
            return (Criteria) this;
        }

        public Criteria andTechnicalPostUIDBetween(Integer value1, Integer value2) {
            addCriterion("TechnicalPostUID between", value1, value2, "technicalPostUID");
            return (Criteria) this;
        }

        public Criteria andTechnicalPostUIDNotBetween(Integer value1, Integer value2) {
            addCriterion("TechnicalPostUID not between", value1, value2, "technicalPostUID");
            return (Criteria) this;
        }

        public Criteria andPositionUIDIsNull() {
            addCriterion("PositionUID is null");
            return (Criteria) this;
        }

        public Criteria andPositionUIDIsNotNull() {
            addCriterion("PositionUID is not null");
            return (Criteria) this;
        }

        public Criteria andPositionUIDEqualTo(Integer value) {
            addCriterion("PositionUID =", value, "positionUID");
            return (Criteria) this;
        }

        public Criteria andPositionUIDNotEqualTo(Integer value) {
            addCriterion("PositionUID <>", value, "positionUID");
            return (Criteria) this;
        }

        public Criteria andPositionUIDGreaterThan(Integer value) {
            addCriterion("PositionUID >", value, "positionUID");
            return (Criteria) this;
        }

        public Criteria andPositionUIDGreaterThanOrEqualTo(Integer value) {
            addCriterion("PositionUID >=", value, "positionUID");
            return (Criteria) this;
        }

        public Criteria andPositionUIDLessThan(Integer value) {
            addCriterion("PositionUID <", value, "positionUID");
            return (Criteria) this;
        }

        public Criteria andPositionUIDLessThanOrEqualTo(Integer value) {
            addCriterion("PositionUID <=", value, "positionUID");
            return (Criteria) this;
        }

        public Criteria andPositionUIDIn(List<Integer> values) {
            addCriterion("PositionUID in", values, "positionUID");
            return (Criteria) this;
        }

        public Criteria andPositionUIDNotIn(List<Integer> values) {
            addCriterion("PositionUID not in", values, "positionUID");
            return (Criteria) this;
        }

        public Criteria andPositionUIDBetween(Integer value1, Integer value2) {
            addCriterion("PositionUID between", value1, value2, "positionUID");
            return (Criteria) this;
        }

        public Criteria andPositionUIDNotBetween(Integer value1, Integer value2) {
            addCriterion("PositionUID not between", value1, value2, "positionUID");
            return (Criteria) this;
        }

        public Criteria andOccupationUIDIsNull() {
            addCriterion("OccupationUID is null");
            return (Criteria) this;
        }

        public Criteria andOccupationUIDIsNotNull() {
            addCriterion("OccupationUID is not null");
            return (Criteria) this;
        }

        public Criteria andOccupationUIDEqualTo(Integer value) {
            addCriterion("OccupationUID =", value, "occupationUID");
            return (Criteria) this;
        }

        public Criteria andOccupationUIDNotEqualTo(Integer value) {
            addCriterion("OccupationUID <>", value, "occupationUID");
            return (Criteria) this;
        }

        public Criteria andOccupationUIDGreaterThan(Integer value) {
            addCriterion("OccupationUID >", value, "occupationUID");
            return (Criteria) this;
        }

        public Criteria andOccupationUIDGreaterThanOrEqualTo(Integer value) {
            addCriterion("OccupationUID >=", value, "occupationUID");
            return (Criteria) this;
        }

        public Criteria andOccupationUIDLessThan(Integer value) {
            addCriterion("OccupationUID <", value, "occupationUID");
            return (Criteria) this;
        }

        public Criteria andOccupationUIDLessThanOrEqualTo(Integer value) {
            addCriterion("OccupationUID <=", value, "occupationUID");
            return (Criteria) this;
        }

        public Criteria andOccupationUIDIn(List<Integer> values) {
            addCriterion("OccupationUID in", values, "occupationUID");
            return (Criteria) this;
        }

        public Criteria andOccupationUIDNotIn(List<Integer> values) {
            addCriterion("OccupationUID not in", values, "occupationUID");
            return (Criteria) this;
        }

        public Criteria andOccupationUIDBetween(Integer value1, Integer value2) {
            addCriterion("OccupationUID between", value1, value2, "occupationUID");
            return (Criteria) this;
        }

        public Criteria andOccupationUIDNotBetween(Integer value1, Integer value2) {
            addCriterion("OccupationUID not between", value1, value2, "occupationUID");
            return (Criteria) this;
        }

        public Criteria andDepartmentUIDIsNull() {
            addCriterion("DepartmentUID is null");
            return (Criteria) this;
        }

        public Criteria andDepartmentUIDIsNotNull() {
            addCriterion("DepartmentUID is not null");
            return (Criteria) this;
        }

        public Criteria andDepartmentUIDEqualTo(Integer value) {
            addCriterion("DepartmentUID =", value, "departmentUID");
            return (Criteria) this;
        }

        public Criteria andDepartmentUIDNotEqualTo(Integer value) {
            addCriterion("DepartmentUID <>", value, "departmentUID");
            return (Criteria) this;
        }

        public Criteria andDepartmentUIDGreaterThan(Integer value) {
            addCriterion("DepartmentUID >", value, "departmentUID");
            return (Criteria) this;
        }

        public Criteria andDepartmentUIDGreaterThanOrEqualTo(Integer value) {
            addCriterion("DepartmentUID >=", value, "departmentUID");
            return (Criteria) this;
        }

        public Criteria andDepartmentUIDLessThan(Integer value) {
            addCriterion("DepartmentUID <", value, "departmentUID");
            return (Criteria) this;
        }

        public Criteria andDepartmentUIDLessThanOrEqualTo(Integer value) {
            addCriterion("DepartmentUID <=", value, "departmentUID");
            return (Criteria) this;
        }

        public Criteria andDepartmentUIDIn(List<Integer> values) {
            addCriterion("DepartmentUID in", values, "departmentUID");
            return (Criteria) this;
        }

        public Criteria andDepartmentUIDNotIn(List<Integer> values) {
            addCriterion("DepartmentUID not in", values, "departmentUID");
            return (Criteria) this;
        }

        public Criteria andDepartmentUIDBetween(Integer value1, Integer value2) {
            addCriterion("DepartmentUID between", value1, value2, "departmentUID");
            return (Criteria) this;
        }

        public Criteria andDepartmentUIDNotBetween(Integer value1, Integer value2) {
            addCriterion("DepartmentUID not between", value1, value2, "departmentUID");
            return (Criteria) this;
        }

        public Criteria andOccupationStatusUIDIsNull() {
            addCriterion("OccupationStatusUID is null");
            return (Criteria) this;
        }

        public Criteria andOccupationStatusUIDIsNotNull() {
            addCriterion("OccupationStatusUID is not null");
            return (Criteria) this;
        }

        public Criteria andOccupationStatusUIDEqualTo(Integer value) {
            addCriterion("OccupationStatusUID =", value, "occupationStatusUID");
            return (Criteria) this;
        }

        public Criteria andOccupationStatusUIDNotEqualTo(Integer value) {
            addCriterion("OccupationStatusUID <>", value, "occupationStatusUID");
            return (Criteria) this;
        }

        public Criteria andOccupationStatusUIDGreaterThan(Integer value) {
            addCriterion("OccupationStatusUID >", value, "occupationStatusUID");
            return (Criteria) this;
        }

        public Criteria andOccupationStatusUIDGreaterThanOrEqualTo(Integer value) {
            addCriterion("OccupationStatusUID >=", value, "occupationStatusUID");
            return (Criteria) this;
        }

        public Criteria andOccupationStatusUIDLessThan(Integer value) {
            addCriterion("OccupationStatusUID <", value, "occupationStatusUID");
            return (Criteria) this;
        }

        public Criteria andOccupationStatusUIDLessThanOrEqualTo(Integer value) {
            addCriterion("OccupationStatusUID <=", value, "occupationStatusUID");
            return (Criteria) this;
        }

        public Criteria andOccupationStatusUIDIn(List<Integer> values) {
            addCriterion("OccupationStatusUID in", values, "occupationStatusUID");
            return (Criteria) this;
        }

        public Criteria andOccupationStatusUIDNotIn(List<Integer> values) {
            addCriterion("OccupationStatusUID not in", values, "occupationStatusUID");
            return (Criteria) this;
        }

        public Criteria andOccupationStatusUIDBetween(Integer value1, Integer value2) {
            addCriterion("OccupationStatusUID between", value1, value2, "occupationStatusUID");
            return (Criteria) this;
        }

        public Criteria andOccupationStatusUIDNotBetween(Integer value1, Integer value2) {
            addCriterion("OccupationStatusUID not between", value1, value2, "occupationStatusUID");
            return (Criteria) this;
        }

        public Criteria andSpecialtyIsNull() {
            addCriterion("Specialty is null");
            return (Criteria) this;
        }

        public Criteria andSpecialtyIsNotNull() {
            addCriterion("Specialty is not null");
            return (Criteria) this;
        }

        public Criteria andSpecialtyEqualTo(String value) {
            addCriterion("Specialty =", value, "specialty");
            return (Criteria) this;
        }

        public Criteria andSpecialtyNotEqualTo(String value) {
            addCriterion("Specialty <>", value, "specialty");
            return (Criteria) this;
        }

        public Criteria andSpecialtyGreaterThan(String value) {
            addCriterion("Specialty >", value, "specialty");
            return (Criteria) this;
        }

        public Criteria andSpecialtyGreaterThanOrEqualTo(String value) {
            addCriterion("Specialty >=", value, "specialty");
            return (Criteria) this;
        }

        public Criteria andSpecialtyLessThan(String value) {
            addCriterion("Specialty <", value, "specialty");
            return (Criteria) this;
        }

        public Criteria andSpecialtyLessThanOrEqualTo(String value) {
            addCriterion("Specialty <=", value, "specialty");
            return (Criteria) this;
        }

        public Criteria andSpecialtyLike(String value) {
            addCriterion("Specialty like", value, "specialty");
            return (Criteria) this;
        }

        public Criteria andSpecialtyNotLike(String value) {
            addCriterion("Specialty not like", value, "specialty");
            return (Criteria) this;
        }

        public Criteria andSpecialtyIn(List<String> values) {
            addCriterion("Specialty in", values, "specialty");
            return (Criteria) this;
        }

        public Criteria andSpecialtyNotIn(List<String> values) {
            addCriterion("Specialty not in", values, "specialty");
            return (Criteria) this;
        }

        public Criteria andSpecialtyBetween(String value1, String value2) {
            addCriterion("Specialty between", value1, value2, "specialty");
            return (Criteria) this;
        }

        public Criteria andSpecialtyNotBetween(String value1, String value2) {
            addCriterion("Specialty not between", value1, value2, "specialty");
            return (Criteria) this;
        }

        public Criteria andIntroduceIsNull() {
            addCriterion("Introduce is null");
            return (Criteria) this;
        }

        public Criteria andIntroduceIsNotNull() {
            addCriterion("Introduce is not null");
            return (Criteria) this;
        }

        public Criteria andIntroduceEqualTo(String value) {
            addCriterion("Introduce =", value, "introduce");
            return (Criteria) this;
        }

        public Criteria andIntroduceNotEqualTo(String value) {
            addCriterion("Introduce <>", value, "introduce");
            return (Criteria) this;
        }

        public Criteria andIntroduceGreaterThan(String value) {
            addCriterion("Introduce >", value, "introduce");
            return (Criteria) this;
        }

        public Criteria andIntroduceGreaterThanOrEqualTo(String value) {
            addCriterion("Introduce >=", value, "introduce");
            return (Criteria) this;
        }

        public Criteria andIntroduceLessThan(String value) {
            addCriterion("Introduce <", value, "introduce");
            return (Criteria) this;
        }

        public Criteria andIntroduceLessThanOrEqualTo(String value) {
            addCriterion("Introduce <=", value, "introduce");
            return (Criteria) this;
        }

        public Criteria andIntroduceLike(String value) {
            addCriterion("Introduce like", value, "introduce");
            return (Criteria) this;
        }

        public Criteria andIntroduceNotLike(String value) {
            addCriterion("Introduce not like", value, "introduce");
            return (Criteria) this;
        }

        public Criteria andIntroduceIn(List<String> values) {
            addCriterion("Introduce in", values, "introduce");
            return (Criteria) this;
        }

        public Criteria andIntroduceNotIn(List<String> values) {
            addCriterion("Introduce not in", values, "introduce");
            return (Criteria) this;
        }

        public Criteria andIntroduceBetween(String value1, String value2) {
            addCriterion("Introduce between", value1, value2, "introduce");
            return (Criteria) this;
        }

        public Criteria andIntroduceNotBetween(String value1, String value2) {
            addCriterion("Introduce not between", value1, value2, "introduce");
            return (Criteria) this;
        }

        public Criteria andCashSetUIDIsNull() {
            addCriterion("CashSetUID is null");
            return (Criteria) this;
        }

        public Criteria andCashSetUIDIsNotNull() {
            addCriterion("CashSetUID is not null");
            return (Criteria) this;
        }

        public Criteria andCashSetUIDEqualTo(Integer value) {
            addCriterion("CashSetUID =", value, "cashSetUID");
            return (Criteria) this;
        }

        public Criteria andCashSetUIDNotEqualTo(Integer value) {
            addCriterion("CashSetUID <>", value, "cashSetUID");
            return (Criteria) this;
        }

        public Criteria andCashSetUIDGreaterThan(Integer value) {
            addCriterion("CashSetUID >", value, "cashSetUID");
            return (Criteria) this;
        }

        public Criteria andCashSetUIDGreaterThanOrEqualTo(Integer value) {
            addCriterion("CashSetUID >=", value, "cashSetUID");
            return (Criteria) this;
        }

        public Criteria andCashSetUIDLessThan(Integer value) {
            addCriterion("CashSetUID <", value, "cashSetUID");
            return (Criteria) this;
        }

        public Criteria andCashSetUIDLessThanOrEqualTo(Integer value) {
            addCriterion("CashSetUID <=", value, "cashSetUID");
            return (Criteria) this;
        }

        public Criteria andCashSetUIDIn(List<Integer> values) {
            addCriterion("CashSetUID in", values, "cashSetUID");
            return (Criteria) this;
        }

        public Criteria andCashSetUIDNotIn(List<Integer> values) {
            addCriterion("CashSetUID not in", values, "cashSetUID");
            return (Criteria) this;
        }

        public Criteria andCashSetUIDBetween(Integer value1, Integer value2) {
            addCriterion("CashSetUID between", value1, value2, "cashSetUID");
            return (Criteria) this;
        }

        public Criteria andCashSetUIDNotBetween(Integer value1, Integer value2) {
            addCriterion("CashSetUID not between", value1, value2, "cashSetUID");
            return (Criteria) this;
        }

        public Criteria andCashTypeUIDIsNull() {
            addCriterion("CashTypeUID is null");
            return (Criteria) this;
        }

        public Criteria andCashTypeUIDIsNotNull() {
            addCriterion("CashTypeUID is not null");
            return (Criteria) this;
        }

        public Criteria andCashTypeUIDEqualTo(Integer value) {
            addCriterion("CashTypeUID =", value, "cashTypeUID");
            return (Criteria) this;
        }

        public Criteria andCashTypeUIDNotEqualTo(Integer value) {
            addCriterion("CashTypeUID <>", value, "cashTypeUID");
            return (Criteria) this;
        }

        public Criteria andCashTypeUIDGreaterThan(Integer value) {
            addCriterion("CashTypeUID >", value, "cashTypeUID");
            return (Criteria) this;
        }

        public Criteria andCashTypeUIDGreaterThanOrEqualTo(Integer value) {
            addCriterion("CashTypeUID >=", value, "cashTypeUID");
            return (Criteria) this;
        }

        public Criteria andCashTypeUIDLessThan(Integer value) {
            addCriterion("CashTypeUID <", value, "cashTypeUID");
            return (Criteria) this;
        }

        public Criteria andCashTypeUIDLessThanOrEqualTo(Integer value) {
            addCriterion("CashTypeUID <=", value, "cashTypeUID");
            return (Criteria) this;
        }

        public Criteria andCashTypeUIDIn(List<Integer> values) {
            addCriterion("CashTypeUID in", values, "cashTypeUID");
            return (Criteria) this;
        }

        public Criteria andCashTypeUIDNotIn(List<Integer> values) {
            addCriterion("CashTypeUID not in", values, "cashTypeUID");
            return (Criteria) this;
        }

        public Criteria andCashTypeUIDBetween(Integer value1, Integer value2) {
            addCriterion("CashTypeUID between", value1, value2, "cashTypeUID");
            return (Criteria) this;
        }

        public Criteria andCashTypeUIDNotBetween(Integer value1, Integer value2) {
            addCriterion("CashTypeUID not between", value1, value2, "cashTypeUID");
            return (Criteria) this;
        }

        public Criteria andStatusIsNull() {
            addCriterion("Status is null");
            return (Criteria) this;
        }

        public Criteria andStatusIsNotNull() {
            addCriterion("Status is not null");
            return (Criteria) this;
        }

        public Criteria andStatusEqualTo(Byte value) {
            addCriterion("Status =", value, "status");
            return (Criteria) this;
        }

        public Criteria andStatusNotEqualTo(Byte value) {
            addCriterion("Status <>", value, "status");
            return (Criteria) this;
        }

        public Criteria andStatusGreaterThan(Byte value) {
            addCriterion("Status >", value, "status");
            return (Criteria) this;
        }

        public Criteria andStatusGreaterThanOrEqualTo(Byte value) {
            addCriterion("Status >=", value, "status");
            return (Criteria) this;
        }

        public Criteria andStatusLessThan(Byte value) {
            addCriterion("Status <", value, "status");
            return (Criteria) this;
        }

        public Criteria andStatusLessThanOrEqualTo(Byte value) {
            addCriterion("Status <=", value, "status");
            return (Criteria) this;
        }

        public Criteria andStatusIn(List<Byte> values) {
            addCriterion("Status in", values, "status");
            return (Criteria) this;
        }

        public Criteria andStatusNotIn(List<Byte> values) {
            addCriterion("Status not in", values, "status");
            return (Criteria) this;
        }

        public Criteria andStatusBetween(Byte value1, Byte value2) {
            addCriterion("Status between", value1, value2, "status");
            return (Criteria) this;
        }

        public Criteria andStatusNotBetween(Byte value1, Byte value2) {
            addCriterion("Status not between", value1, value2, "status");
            return (Criteria) this;
        }

        public Criteria andIsSystemRegisteredIsNull() {
            addCriterion("IsSystemRegistered is null");
            return (Criteria) this;
        }

        public Criteria andIsSystemRegisteredIsNotNull() {
            addCriterion("IsSystemRegistered is not null");
            return (Criteria) this;
        }

        public Criteria andIsSystemRegisteredEqualTo(Byte value) {
            addCriterion("IsSystemRegistered =", value, "isSystemRegistered");
            return (Criteria) this;
        }

        public Criteria andIsSystemRegisteredNotEqualTo(Byte value) {
            addCriterion("IsSystemRegistered <>", value, "isSystemRegistered");
            return (Criteria) this;
        }

        public Criteria andIsSystemRegisteredGreaterThan(Byte value) {
            addCriterion("IsSystemRegistered >", value, "isSystemRegistered");
            return (Criteria) this;
        }

        public Criteria andIsSystemRegisteredGreaterThanOrEqualTo(Byte value) {
            addCriterion("IsSystemRegistered >=", value, "isSystemRegistered");
            return (Criteria) this;
        }

        public Criteria andIsSystemRegisteredLessThan(Byte value) {
            addCriterion("IsSystemRegistered <", value, "isSystemRegistered");
            return (Criteria) this;
        }

        public Criteria andIsSystemRegisteredLessThanOrEqualTo(Byte value) {
            addCriterion("IsSystemRegistered <=", value, "isSystemRegistered");
            return (Criteria) this;
        }

        public Criteria andIsSystemRegisteredIn(List<Byte> values) {
            addCriterion("IsSystemRegistered in", values, "isSystemRegistered");
            return (Criteria) this;
        }

        public Criteria andIsSystemRegisteredNotIn(List<Byte> values) {
            addCriterion("IsSystemRegistered not in", values, "isSystemRegistered");
            return (Criteria) this;
        }

        public Criteria andIsSystemRegisteredBetween(Byte value1, Byte value2) {
            addCriterion("IsSystemRegistered between", value1, value2, "isSystemRegistered");
            return (Criteria) this;
        }

        public Criteria andIsSystemRegisteredNotBetween(Byte value1, Byte value2) {
            addCriterion("IsSystemRegistered not between", value1, value2, "isSystemRegistered");
            return (Criteria) this;
        }

        public Criteria andTokenIsNull() {
            addCriterion("token is null");
            return (Criteria) this;
        }

        public Criteria andTokenIsNotNull() {
            addCriterion("token is not null");
            return (Criteria) this;
        }

        public Criteria andTokenEqualTo(String value) {
            addCriterion("token =", value, "token");
            return (Criteria) this;
        }

        public Criteria andTokenNotEqualTo(String value) {
            addCriterion("token <>", value, "token");
            return (Criteria) this;
        }

        public Criteria andTokenGreaterThan(String value) {
            addCriterion("token >", value, "token");
            return (Criteria) this;
        }

        public Criteria andTokenGreaterThanOrEqualTo(String value) {
            addCriterion("token >=", value, "token");
            return (Criteria) this;
        }

        public Criteria andTokenLessThan(String value) {
            addCriterion("token <", value, "token");
            return (Criteria) this;
        }

        public Criteria andTokenLessThanOrEqualTo(String value) {
            addCriterion("token <=", value, "token");
            return (Criteria) this;
        }

        public Criteria andTokenLike(String value) {
            addCriterion("token like", value, "token");
            return (Criteria) this;
        }

        public Criteria andTokenNotLike(String value) {
            addCriterion("token not like", value, "token");
            return (Criteria) this;
        }

        public Criteria andTokenIn(List<String> values) {
            addCriterion("token in", values, "token");
            return (Criteria) this;
        }

        public Criteria andTokenNotIn(List<String> values) {
            addCriterion("token not in", values, "token");
            return (Criteria) this;
        }

        public Criteria andTokenBetween(String value1, String value2) {
            addCriterion("token between", value1, value2, "token");
            return (Criteria) this;
        }

        public Criteria andTokenNotBetween(String value1, String value2) {
            addCriterion("token not between", value1, value2, "token");
            return (Criteria) this;
        }

        public Criteria andCreateTimeIsNull() {
            addCriterion("CreateTime is null");
            return (Criteria) this;
        }

        public Criteria andCreateTimeIsNotNull() {
            addCriterion("CreateTime is not null");
            return (Criteria) this;
        }

        public Criteria andCreateTimeEqualTo(Date value) {
            addCriterion("CreateTime =", value, "createTime");
            return (Criteria) this;
        }

        public Criteria andCreateTimeNotEqualTo(Date value) {
            addCriterion("CreateTime <>", value, "createTime");
            return (Criteria) this;
        }

        public Criteria andCreateTimeGreaterThan(Date value) {
            addCriterion("CreateTime >", value, "createTime");
            return (Criteria) this;
        }

        public Criteria andCreateTimeGreaterThanOrEqualTo(Date value) {
            addCriterion("CreateTime >=", value, "createTime");
            return (Criteria) this;
        }

        public Criteria andCreateTimeLessThan(Date value) {
            addCriterion("CreateTime <", value, "createTime");
            return (Criteria) this;
        }

        public Criteria andCreateTimeLessThanOrEqualTo(Date value) {
            addCriterion("CreateTime <=", value, "createTime");
            return (Criteria) this;
        }

        public Criteria andCreateTimeIn(List<Date> values) {
            addCriterion("CreateTime in", values, "createTime");
            return (Criteria) this;
        }

        public Criteria andCreateTimeNotIn(List<Date> values) {
            addCriterion("CreateTime not in", values, "createTime");
            return (Criteria) this;
        }

        public Criteria andCreateTimeBetween(Date value1, Date value2) {
            addCriterion("CreateTime between", value1, value2, "createTime");
            return (Criteria) this;
        }

        public Criteria andCreateTimeNotBetween(Date value1, Date value2) {
            addCriterion("CreateTime not between", value1, value2, "createTime");
            return (Criteria) this;
        }

        public Criteria andNumberIsNull() {
            addCriterion("Number is null");
            return (Criteria) this;
        }

        public Criteria andNumberIsNotNull() {
            addCriterion("Number is not null");
            return (Criteria) this;
        }

        public Criteria andNumberEqualTo(String value) {
            addCriterion("Number =", value, "number");
            return (Criteria) this;
        }

        public Criteria andNumberNotEqualTo(String value) {
            addCriterion("Number <>", value, "number");
            return (Criteria) this;
        }

        public Criteria andNumberGreaterThan(String value) {
            addCriterion("Number >", value, "number");
            return (Criteria) this;
        }

        public Criteria andNumberGreaterThanOrEqualTo(String value) {
            addCriterion("Number >=", value, "number");
            return (Criteria) this;
        }

        public Criteria andNumberLessThan(String value) {
            addCriterion("Number <", value, "number");
            return (Criteria) this;
        }

        public Criteria andNumberLessThanOrEqualTo(String value) {
            addCriterion("Number <=", value, "number");
            return (Criteria) this;
        }

        public Criteria andNumberLike(String value) {
            addCriterion("Number like", value, "number");
            return (Criteria) this;
        }

        public Criteria andNumberNotLike(String value) {
            addCriterion("Number not like", value, "number");
            return (Criteria) this;
        }

        public Criteria andNumberIn(List<String> values) {
            addCriterion("Number in", values, "number");
            return (Criteria) this;
        }

        public Criteria andNumberNotIn(List<String> values) {
            addCriterion("Number not in", values, "number");
            return (Criteria) this;
        }

        public Criteria andNumberBetween(String value1, String value2) {
            addCriterion("Number between", value1, value2, "number");
            return (Criteria) this;
        }

        public Criteria andNumberNotBetween(String value1, String value2) {
            addCriterion("Number not between", value1, value2, "number");
            return (Criteria) this;
        }

        public Criteria andDisableCauseIsNull() {
            addCriterion("DisableCause is null");
            return (Criteria) this;
        }

        public Criteria andDisableCauseIsNotNull() {
            addCriterion("DisableCause is not null");
            return (Criteria) this;
        }

        public Criteria andDisableCauseEqualTo(String value) {
            addCriterion("DisableCause =", value, "disableCause");
            return (Criteria) this;
        }

        public Criteria andDisableCauseNotEqualTo(String value) {
            addCriterion("DisableCause <>", value, "disableCause");
            return (Criteria) this;
        }

        public Criteria andDisableCauseGreaterThan(String value) {
            addCriterion("DisableCause >", value, "disableCause");
            return (Criteria) this;
        }

        public Criteria andDisableCauseGreaterThanOrEqualTo(String value) {
            addCriterion("DisableCause >=", value, "disableCause");
            return (Criteria) this;
        }

        public Criteria andDisableCauseLessThan(String value) {
            addCriterion("DisableCause <", value, "disableCause");
            return (Criteria) this;
        }

        public Criteria andDisableCauseLessThanOrEqualTo(String value) {
            addCriterion("DisableCause <=", value, "disableCause");
            return (Criteria) this;
        }

        public Criteria andDisableCauseLike(String value) {
            addCriterion("DisableCause like", value, "disableCause");
            return (Criteria) this;
        }

        public Criteria andDisableCauseNotLike(String value) {
            addCriterion("DisableCause not like", value, "disableCause");
            return (Criteria) this;
        }

        public Criteria andDisableCauseIn(List<String> values) {
            addCriterion("DisableCause in", values, "disableCause");
            return (Criteria) this;
        }

        public Criteria andDisableCauseNotIn(List<String> values) {
            addCriterion("DisableCause not in", values, "disableCause");
            return (Criteria) this;
        }

        public Criteria andDisableCauseBetween(String value1, String value2) {
            addCriterion("DisableCause between", value1, value2, "disableCause");
            return (Criteria) this;
        }

        public Criteria andDisableCauseNotBetween(String value1, String value2) {
            addCriterion("DisableCause not between", value1, value2, "disableCause");
            return (Criteria) this;
        }

        public Criteria andIsDeletedIsNull() {
            addCriterion("IsDeleted is null");
            return (Criteria) this;
        }

        public Criteria andIsDeletedIsNotNull() {
            addCriterion("IsDeleted is not null");
            return (Criteria) this;
        }

        public Criteria andIsDeletedEqualTo(Byte value) {
            addCriterion("IsDeleted =", value, "isDeleted");
            return (Criteria) this;
        }

        public Criteria andIsDeletedNotEqualTo(Byte value) {
            addCriterion("IsDeleted <>", value, "isDeleted");
            return (Criteria) this;
        }

        public Criteria andIsDeletedGreaterThan(Byte value) {
            addCriterion("IsDeleted >", value, "isDeleted");
            return (Criteria) this;
        }

        public Criteria andIsDeletedGreaterThanOrEqualTo(Byte value) {
            addCriterion("IsDeleted >=", value, "isDeleted");
            return (Criteria) this;
        }

        public Criteria andIsDeletedLessThan(Byte value) {
            addCriterion("IsDeleted <", value, "isDeleted");
            return (Criteria) this;
        }

        public Criteria andIsDeletedLessThanOrEqualTo(Byte value) {
            addCriterion("IsDeleted <=", value, "isDeleted");
            return (Criteria) this;
        }

        public Criteria andIsDeletedIn(List<Byte> values) {
            addCriterion("IsDeleted in", values, "isDeleted");
            return (Criteria) this;
        }

        public Criteria andIsDeletedNotIn(List<Byte> values) {
            addCriterion("IsDeleted not in", values, "isDeleted");
            return (Criteria) this;
        }

        public Criteria andIsDeletedBetween(Byte value1, Byte value2) {
            addCriterion("IsDeleted between", value1, value2, "isDeleted");
            return (Criteria) this;
        }

        public Criteria andIsDeletedNotBetween(Byte value1, Byte value2) {
            addCriterion("IsDeleted not between", value1, value2, "isDeleted");
            return (Criteria) this;
        }

        public Criteria andMedicalGroupUIDIsNull() {
            addCriterion("MedicalGroupUID is null");
            return (Criteria) this;
        }

        public Criteria andMedicalGroupUIDIsNotNull() {
            addCriterion("MedicalGroupUID is not null");
            return (Criteria) this;
        }

        public Criteria andMedicalGroupUIDEqualTo(Integer value) {
            addCriterion("MedicalGroupUID =", value, "medicalGroupUID");
            return (Criteria) this;
        }

        public Criteria andMedicalGroupUIDNotEqualTo(Integer value) {
            addCriterion("MedicalGroupUID <>", value, "medicalGroupUID");
            return (Criteria) this;
        }

        public Criteria andMedicalGroupUIDGreaterThan(Integer value) {
            addCriterion("MedicalGroupUID >", value, "medicalGroupUID");
            return (Criteria) this;
        }

        public Criteria andMedicalGroupUIDGreaterThanOrEqualTo(Integer value) {
            addCriterion("MedicalGroupUID >=", value, "medicalGroupUID");
            return (Criteria) this;
        }

        public Criteria andMedicalGroupUIDLessThan(Integer value) {
            addCriterion("MedicalGroupUID <", value, "medicalGroupUID");
            return (Criteria) this;
        }

        public Criteria andMedicalGroupUIDLessThanOrEqualTo(Integer value) {
            addCriterion("MedicalGroupUID <=", value, "medicalGroupUID");
            return (Criteria) this;
        }

        public Criteria andMedicalGroupUIDIn(List<Integer> values) {
            addCriterion("MedicalGroupUID in", values, "medicalGroupUID");
            return (Criteria) this;
        }

        public Criteria andMedicalGroupUIDNotIn(List<Integer> values) {
            addCriterion("MedicalGroupUID not in", values, "medicalGroupUID");
            return (Criteria) this;
        }

        public Criteria andMedicalGroupUIDBetween(Integer value1, Integer value2) {
            addCriterion("MedicalGroupUID between", value1, value2, "medicalGroupUID");
            return (Criteria) this;
        }

        public Criteria andMedicalGroupUIDNotBetween(Integer value1, Integer value2) {
            addCriterion("MedicalGroupUID not between", value1, value2, "medicalGroupUID");
            return (Criteria) this;
        }

        public Criteria andGroupPositionUIDIsNull() {
            addCriterion("GroupPositionUID is null");
            return (Criteria) this;
        }

        public Criteria andGroupPositionUIDIsNotNull() {
            addCriterion("GroupPositionUID is not null");
            return (Criteria) this;
        }

        public Criteria andGroupPositionUIDEqualTo(Integer value) {
            addCriterion("GroupPositionUID =", value, "groupPositionUID");
            return (Criteria) this;
        }

        public Criteria andGroupPositionUIDNotEqualTo(Integer value) {
            addCriterion("GroupPositionUID <>", value, "groupPositionUID");
            return (Criteria) this;
        }

        public Criteria andGroupPositionUIDGreaterThan(Integer value) {
            addCriterion("GroupPositionUID >", value, "groupPositionUID");
            return (Criteria) this;
        }

        public Criteria andGroupPositionUIDGreaterThanOrEqualTo(Integer value) {
            addCriterion("GroupPositionUID >=", value, "groupPositionUID");
            return (Criteria) this;
        }

        public Criteria andGroupPositionUIDLessThan(Integer value) {
            addCriterion("GroupPositionUID <", value, "groupPositionUID");
            return (Criteria) this;
        }

        public Criteria andGroupPositionUIDLessThanOrEqualTo(Integer value) {
            addCriterion("GroupPositionUID <=", value, "groupPositionUID");
            return (Criteria) this;
        }

        public Criteria andGroupPositionUIDIn(List<Integer> values) {
            addCriterion("GroupPositionUID in", values, "groupPositionUID");
            return (Criteria) this;
        }

        public Criteria andGroupPositionUIDNotIn(List<Integer> values) {
            addCriterion("GroupPositionUID not in", values, "groupPositionUID");
            return (Criteria) this;
        }

        public Criteria andGroupPositionUIDBetween(Integer value1, Integer value2) {
            addCriterion("GroupPositionUID between", value1, value2, "groupPositionUID");
            return (Criteria) this;
        }

        public Criteria andGroupPositionUIDNotBetween(Integer value1, Integer value2) {
            addCriterion("GroupPositionUID not between", value1, value2, "groupPositionUID");
            return (Criteria) this;
        }

        public Criteria andAesKeyIsNull() {
            addCriterion("AesKey is null");
            return (Criteria) this;
        }

        public Criteria andAesKeyIsNotNull() {
            addCriterion("AesKey is not null");
            return (Criteria) this;
        }

        public Criteria andAesKeyEqualTo(String value) {
            addCriterion("AesKey =", value, "aesKey");
            return (Criteria) this;
        }

        public Criteria andAesKeyNotEqualTo(String value) {
            addCriterion("AesKey <>", value, "aesKey");
            return (Criteria) this;
        }

        public Criteria andAesKeyGreaterThan(String value) {
            addCriterion("AesKey >", value, "aesKey");
            return (Criteria) this;
        }

        public Criteria andAesKeyGreaterThanOrEqualTo(String value) {
            addCriterion("AesKey >=", value, "aesKey");
            return (Criteria) this;
        }

        public Criteria andAesKeyLessThan(String value) {
            addCriterion("AesKey <", value, "aesKey");
            return (Criteria) this;
        }

        public Criteria andAesKeyLessThanOrEqualTo(String value) {
            addCriterion("AesKey <=", value, "aesKey");
            return (Criteria) this;
        }

        public Criteria andAesKeyLike(String value) {
            addCriterion("AesKey like", value, "aesKey");
            return (Criteria) this;
        }

        public Criteria andAesKeyNotLike(String value) {
            addCriterion("AesKey not like", value, "aesKey");
            return (Criteria) this;
        }

        public Criteria andAesKeyIn(List<String> values) {
            addCriterion("AesKey in", values, "aesKey");
            return (Criteria) this;
        }

        public Criteria andAesKeyNotIn(List<String> values) {
            addCriterion("AesKey not in", values, "aesKey");
            return (Criteria) this;
        }

        public Criteria andAesKeyBetween(String value1, String value2) {
            addCriterion("AesKey between", value1, value2, "aesKey");
            return (Criteria) this;
        }

        public Criteria andAesKeyNotBetween(String value1, String value2) {
            addCriterion("AesKey not between", value1, value2, "aesKey");
            return (Criteria) this;
        }

        public Criteria andTotalScoreIsNull() {
            addCriterion("TotalScore is null");
            return (Criteria) this;
        }

        public Criteria andTotalScoreIsNotNull() {
            addCriterion("TotalScore is not null");
            return (Criteria) this;
        }

        public Criteria andTotalScoreEqualTo(Integer value) {
            addCriterion("TotalScore =", value, "totalScore");
            return (Criteria) this;
        }

        public Criteria andTotalScoreNotEqualTo(Integer value) {
            addCriterion("TotalScore <>", value, "totalScore");
            return (Criteria) this;
        }

        public Criteria andTotalScoreGreaterThan(Integer value) {
            addCriterion("TotalScore >", value, "totalScore");
            return (Criteria) this;
        }

        public Criteria andTotalScoreGreaterThanOrEqualTo(Integer value) {
            addCriterion("TotalScore >=", value, "totalScore");
            return (Criteria) this;
        }

        public Criteria andTotalScoreLessThan(Integer value) {
            addCriterion("TotalScore <", value, "totalScore");
            return (Criteria) this;
        }

        public Criteria andTotalScoreLessThanOrEqualTo(Integer value) {
            addCriterion("TotalScore <=", value, "totalScore");
            return (Criteria) this;
        }

        public Criteria andTotalScoreIn(List<Integer> values) {
            addCriterion("TotalScore in", values, "totalScore");
            return (Criteria) this;
        }

        public Criteria andTotalScoreNotIn(List<Integer> values) {
            addCriterion("TotalScore not in", values, "totalScore");
            return (Criteria) this;
        }

        public Criteria andTotalScoreBetween(Integer value1, Integer value2) {
            addCriterion("TotalScore between", value1, value2, "totalScore");
            return (Criteria) this;
        }

        public Criteria andTotalScoreNotBetween(Integer value1, Integer value2) {
            addCriterion("TotalScore not between", value1, value2, "totalScore");
            return (Criteria) this;
        }

        public Criteria andRegisterTimeIsNull() {
            addCriterion("RegisterTime is null");
            return (Criteria) this;
        }

        public Criteria andRegisterTimeIsNotNull() {
            addCriterion("RegisterTime is not null");
            return (Criteria) this;
        }

        public Criteria andRegisterTimeEqualTo(Date value) {
            addCriterion("RegisterTime =", value, "registerTime");
            return (Criteria) this;
        }

        public Criteria andRegisterTimeNotEqualTo(Date value) {
            addCriterion("RegisterTime <>", value, "registerTime");
            return (Criteria) this;
        }

        public Criteria andRegisterTimeGreaterThan(Date value) {
            addCriterion("RegisterTime >", value, "registerTime");
            return (Criteria) this;
        }

        public Criteria andRegisterTimeGreaterThanOrEqualTo(Date value) {
            addCriterion("RegisterTime >=", value, "registerTime");
            return (Criteria) this;
        }

        public Criteria andRegisterTimeLessThan(Date value) {
            addCriterion("RegisterTime <", value, "registerTime");
            return (Criteria) this;
        }

        public Criteria andRegisterTimeLessThanOrEqualTo(Date value) {
            addCriterion("RegisterTime <=", value, "registerTime");
            return (Criteria) this;
        }

        public Criteria andRegisterTimeIn(List<Date> values) {
            addCriterion("RegisterTime in", values, "registerTime");
            return (Criteria) this;
        }

        public Criteria andRegisterTimeNotIn(List<Date> values) {
            addCriterion("RegisterTime not in", values, "registerTime");
            return (Criteria) this;
        }

        public Criteria andRegisterTimeBetween(Date value1, Date value2) {
            addCriterion("RegisterTime between", value1, value2, "registerTime");
            return (Criteria) this;
        }

        public Criteria andRegisterTimeNotBetween(Date value1, Date value2) {
            addCriterion("RegisterTime not between", value1, value2, "registerTime");
            return (Criteria) this;
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table tb_doctor
     *
     * @mbggenerated do_not_delete_during_merge
     */
    public static class Criteria extends GeneratedCriteria {

        protected Criteria() {
            super();
        }

        public Criteria andRtisDoctorUIDLikeInsensitive(String value) {
            addCriterion("upper(RtisDoctorUID) like", value.toUpperCase(), "rtisDoctorUID");
            return this;
        }

        public Criteria andPasswordLikeInsensitive(String value) {
            addCriterion("upper(Password) like", value.toUpperCase(), "password");
            return this;
        }

        public Criteria andDoctorNameLikeInsensitive(String value) {
            addCriterion("upper(DoctorName) like", value.toUpperCase(), "doctorName");
            return this;
        }

        public Criteria andAppCellPhoneLikeInsensitive(String value) {
            addCriterion("upper(AppCellPhone) like", value.toUpperCase(), "appCellPhone");
            return this;
        }

        public Criteria andCellPhoneLikeInsensitive(String value) {
            addCriterion("upper(CellPhone) like", value.toUpperCase(), "cellPhone");
            return this;
        }

        public Criteria andNativePlaceLikeInsensitive(String value) {
            addCriterion("upper(NativePlace) like", value.toUpperCase(), "nativePlace");
            return this;
        }

        public Criteria andNationalityLikeInsensitive(String value) {
            addCriterion("upper(Nationality) like", value.toUpperCase(), "nationality");
            return this;
        }

        public Criteria andStationaryPhoneLikeInsensitive(String value) {
            addCriterion("upper(StationaryPhone) like", value.toUpperCase(), "stationaryPhone");
            return this;
        }

        public Criteria andAddressLikeInsensitive(String value) {
            addCriterion("upper(Address) like", value.toUpperCase(), "address");
            return this;
        }

        public Criteria andPicturlURLLikeInsensitive(String value) {
            addCriterion("upper(PicturlURL) like", value.toUpperCase(), "picturlURL");
            return this;
        }

        public Criteria andSexLikeInsensitive(String value) {
            addCriterion("upper(Sex) like", value.toUpperCase(), "sex");
            return this;
        }

        public Criteria andIDNumberLikeInsensitive(String value) {
            addCriterion("upper(IDNumber) like", value.toUpperCase(), "IDNumber");
            return this;
        }

        public Criteria andSpecialtyLikeInsensitive(String value) {
            addCriterion("upper(Specialty) like", value.toUpperCase(), "specialty");
            return this;
        }

        public Criteria andIntroduceLikeInsensitive(String value) {
            addCriterion("upper(Introduce) like", value.toUpperCase(), "introduce");
            return this;
        }

        public Criteria andTokenLikeInsensitive(String value) {
            addCriterion("upper(token) like", value.toUpperCase(), "token");
            return this;
        }

        public Criteria andNumberLikeInsensitive(String value) {
            addCriterion("upper(Number) like", value.toUpperCase(), "number");
            return this;
        }

        public Criteria andDisableCauseLikeInsensitive(String value) {
            addCriterion("upper(DisableCause) like", value.toUpperCase(), "disableCause");
            return this;
        }

        public Criteria andAesKeyLikeInsensitive(String value) {
            addCriterion("upper(AesKey) like", value.toUpperCase(), "aesKey");
            return this;
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table tb_doctor
     *
     * @mbggenerated
     */
    public static class Criterion {
        private String condition;

        private Object value;

        private Object secondValue;

        private boolean noValue;

        private boolean singleValue;

        private boolean betweenValue;

        private boolean listValue;

        public String getCondition() {
            return condition;
        }

        public Object getValue() {
            return value;
        }

        public Object getSecondValue() {
            return secondValue;
        }

        public boolean isNoValue() {
            return noValue;
        }

        public boolean isSingleValue() {
            return singleValue;
        }

        public boolean isBetweenValue() {
            return betweenValue;
        }

        public boolean isListValue() {
            return listValue;
        }

        protected Criterion(String condition) {
            super();
            this.condition = condition;
            this.noValue = true;
        }

        protected Criterion(String condition, Object value) {
            super();
            this.condition = condition;
            this.value = value;
            if (value instanceof List<?>) {
                this.listValue = true;
            } else {
                this.singleValue = true;
            }
        }

        protected Criterion(String condition, Object value, Object secondValue) {
            super();
            this.condition = condition;
            this.value = value;
            this.secondValue = secondValue;
            this.betweenValue = true;
        }
    }
}