package org.zcgewu.study.soa.service.doctor.po;

import java.util.ArrayList;
import java.util.Date;
import java.util.List;

public class AppPermissionExample {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table tb_app_permission
     *
     * @mbggenerated
     */
    protected String orderByClause;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table tb_app_permission
     *
     * @mbggenerated
     */
    protected boolean distinct;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table tb_app_permission
     *
     * @mbggenerated
     */
    protected List<Criteria> oredCriteria;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table tb_app_permission
     *
     * @mbggenerated
     */
    protected Integer limitStart;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table tb_app_permission
     *
     * @mbggenerated
     */
    protected Integer limitEnd;

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_app_permission
     *
     * @mbggenerated
     */
    public AppPermissionExample() {
        oredCriteria = new ArrayList<Criteria>();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_app_permission
     *
     * @mbggenerated
     */
    public void setOrderByClause(String orderByClause) {
        this.orderByClause = orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_app_permission
     *
     * @mbggenerated
     */
    public String getOrderByClause() {
        return orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_app_permission
     *
     * @mbggenerated
     */
    public void setDistinct(boolean distinct) {
        this.distinct = distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_app_permission
     *
     * @mbggenerated
     */
    public boolean isDistinct() {
        return distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_app_permission
     *
     * @mbggenerated
     */
    public List<Criteria> getOredCriteria() {
        return oredCriteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_app_permission
     *
     * @mbggenerated
     */
    public void or(Criteria criteria) {
        oredCriteria.add(criteria);
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_app_permission
     *
     * @mbggenerated
     */
    public Criteria or() {
        Criteria criteria = createCriteriaInternal();
        oredCriteria.add(criteria);
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_app_permission
     *
     * @mbggenerated
     */
    public Criteria createCriteria() {
        Criteria criteria = createCriteriaInternal();
        if (oredCriteria.size() == 0) {
            oredCriteria.add(criteria);
        }
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_app_permission
     *
     * @mbggenerated
     */
    protected Criteria createCriteriaInternal() {
        Criteria criteria = new Criteria();
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_app_permission
     *
     * @mbggenerated
     */
    public void clear() {
        oredCriteria.clear();
        orderByClause = null;
        distinct = false;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_app_permission
     *
     * @mbggenerated
     */
    public void setLimitStart(Integer limitStart) {
        this.limitStart=limitStart;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_app_permission
     *
     * @mbggenerated
     */
    public Integer getLimitStart() {
        return limitStart;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_app_permission
     *
     * @mbggenerated
     */
    public void setLimitEnd(Integer limitEnd) {
        this.limitEnd=limitEnd;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_app_permission
     *
     * @mbggenerated
     */
    public Integer getLimitEnd() {
        return limitEnd;
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table tb_app_permission
     *
     * @mbggenerated
     */
    protected abstract static class GeneratedCriteria {
        protected List<Criterion> criteria;

        protected GeneratedCriteria() {
            super();
            criteria = new ArrayList<Criterion>();
        }

        public boolean isValid() {
            return criteria.size() > 0;
        }

        public List<Criterion> getCriteria() {
            return criteria;
        }

        protected void addCriterion(String condition) {
            if (condition == null) {
                throw new RuntimeException("Value for condition cannot be null");
            }
            criteria.add(new Criterion(condition));
        }

        protected void addCriterion(String condition, Object value, String property) {
            if (value == null) {
                throw new RuntimeException("Value for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value));
        }

        protected void addCriterion(String condition, Object value1, Object value2, String property) {
            if (value1 == null || value2 == null) {
                throw new RuntimeException("Between values for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value1, value2));
        }

        public Criteria andAppPermissionUidIsNull() {
            addCriterion("app_permission_uid is null");
            return (Criteria) this;
        }

        public Criteria andAppPermissionUidIsNotNull() {
            addCriterion("app_permission_uid is not null");
            return (Criteria) this;
        }

        public Criteria andAppPermissionUidEqualTo(Integer value) {
            addCriterion("app_permission_uid =", value, "appPermissionUid");
            return (Criteria) this;
        }

        public Criteria andAppPermissionUidNotEqualTo(Integer value) {
            addCriterion("app_permission_uid <>", value, "appPermissionUid");
            return (Criteria) this;
        }

        public Criteria andAppPermissionUidGreaterThan(Integer value) {
            addCriterion("app_permission_uid >", value, "appPermissionUid");
            return (Criteria) this;
        }

        public Criteria andAppPermissionUidGreaterThanOrEqualTo(Integer value) {
            addCriterion("app_permission_uid >=", value, "appPermissionUid");
            return (Criteria) this;
        }

        public Criteria andAppPermissionUidLessThan(Integer value) {
            addCriterion("app_permission_uid <", value, "appPermissionUid");
            return (Criteria) this;
        }

        public Criteria andAppPermissionUidLessThanOrEqualTo(Integer value) {
            addCriterion("app_permission_uid <=", value, "appPermissionUid");
            return (Criteria) this;
        }

        public Criteria andAppPermissionUidIn(List<Integer> values) {
            addCriterion("app_permission_uid in", values, "appPermissionUid");
            return (Criteria) this;
        }

        public Criteria andAppPermissionUidNotIn(List<Integer> values) {
            addCriterion("app_permission_uid not in", values, "appPermissionUid");
            return (Criteria) this;
        }

        public Criteria andAppPermissionUidBetween(Integer value1, Integer value2) {
            addCriterion("app_permission_uid between", value1, value2, "appPermissionUid");
            return (Criteria) this;
        }

        public Criteria andAppPermissionUidNotBetween(Integer value1, Integer value2) {
            addCriterion("app_permission_uid not between", value1, value2, "appPermissionUid");
            return (Criteria) this;
        }

        public Criteria andAppPermissionNoIsNull() {
            addCriterion("app_permission_no is null");
            return (Criteria) this;
        }

        public Criteria andAppPermissionNoIsNotNull() {
            addCriterion("app_permission_no is not null");
            return (Criteria) this;
        }

        public Criteria andAppPermissionNoEqualTo(String value) {
            addCriterion("app_permission_no =", value, "appPermissionNo");
            return (Criteria) this;
        }

        public Criteria andAppPermissionNoNotEqualTo(String value) {
            addCriterion("app_permission_no <>", value, "appPermissionNo");
            return (Criteria) this;
        }

        public Criteria andAppPermissionNoGreaterThan(String value) {
            addCriterion("app_permission_no >", value, "appPermissionNo");
            return (Criteria) this;
        }

        public Criteria andAppPermissionNoGreaterThanOrEqualTo(String value) {
            addCriterion("app_permission_no >=", value, "appPermissionNo");
            return (Criteria) this;
        }

        public Criteria andAppPermissionNoLessThan(String value) {
            addCriterion("app_permission_no <", value, "appPermissionNo");
            return (Criteria) this;
        }

        public Criteria andAppPermissionNoLessThanOrEqualTo(String value) {
            addCriterion("app_permission_no <=", value, "appPermissionNo");
            return (Criteria) this;
        }

        public Criteria andAppPermissionNoLike(String value) {
            addCriterion("app_permission_no like", value, "appPermissionNo");
            return (Criteria) this;
        }

        public Criteria andAppPermissionNoNotLike(String value) {
            addCriterion("app_permission_no not like", value, "appPermissionNo");
            return (Criteria) this;
        }

        public Criteria andAppPermissionNoIn(List<String> values) {
            addCriterion("app_permission_no in", values, "appPermissionNo");
            return (Criteria) this;
        }

        public Criteria andAppPermissionNoNotIn(List<String> values) {
            addCriterion("app_permission_no not in", values, "appPermissionNo");
            return (Criteria) this;
        }

        public Criteria andAppPermissionNoBetween(String value1, String value2) {
            addCriterion("app_permission_no between", value1, value2, "appPermissionNo");
            return (Criteria) this;
        }

        public Criteria andAppPermissionNoNotBetween(String value1, String value2) {
            addCriterion("app_permission_no not between", value1, value2, "appPermissionNo");
            return (Criteria) this;
        }

        public Criteria andAppPermissionNameIsNull() {
            addCriterion("app_permission_name is null");
            return (Criteria) this;
        }

        public Criteria andAppPermissionNameIsNotNull() {
            addCriterion("app_permission_name is not null");
            return (Criteria) this;
        }

        public Criteria andAppPermissionNameEqualTo(String value) {
            addCriterion("app_permission_name =", value, "appPermissionName");
            return (Criteria) this;
        }

        public Criteria andAppPermissionNameNotEqualTo(String value) {
            addCriterion("app_permission_name <>", value, "appPermissionName");
            return (Criteria) this;
        }

        public Criteria andAppPermissionNameGreaterThan(String value) {
            addCriterion("app_permission_name >", value, "appPermissionName");
            return (Criteria) this;
        }

        public Criteria andAppPermissionNameGreaterThanOrEqualTo(String value) {
            addCriterion("app_permission_name >=", value, "appPermissionName");
            return (Criteria) this;
        }

        public Criteria andAppPermissionNameLessThan(String value) {
            addCriterion("app_permission_name <", value, "appPermissionName");
            return (Criteria) this;
        }

        public Criteria andAppPermissionNameLessThanOrEqualTo(String value) {
            addCriterion("app_permission_name <=", value, "appPermissionName");
            return (Criteria) this;
        }

        public Criteria andAppPermissionNameLike(String value) {
            addCriterion("app_permission_name like", value, "appPermissionName");
            return (Criteria) this;
        }

        public Criteria andAppPermissionNameNotLike(String value) {
            addCriterion("app_permission_name not like", value, "appPermissionName");
            return (Criteria) this;
        }

        public Criteria andAppPermissionNameIn(List<String> values) {
            addCriterion("app_permission_name in", values, "appPermissionName");
            return (Criteria) this;
        }

        public Criteria andAppPermissionNameNotIn(List<String> values) {
            addCriterion("app_permission_name not in", values, "appPermissionName");
            return (Criteria) this;
        }

        public Criteria andAppPermissionNameBetween(String value1, String value2) {
            addCriterion("app_permission_name between", value1, value2, "appPermissionName");
            return (Criteria) this;
        }

        public Criteria andAppPermissionNameNotBetween(String value1, String value2) {
            addCriterion("app_permission_name not between", value1, value2, "appPermissionName");
            return (Criteria) this;
        }

        public Criteria andAppPermissionTypeIsNull() {
            addCriterion("app_permission_type is null");
            return (Criteria) this;
        }

        public Criteria andAppPermissionTypeIsNotNull() {
            addCriterion("app_permission_type is not null");
            return (Criteria) this;
        }

        public Criteria andAppPermissionTypeEqualTo(Byte value) {
            addCriterion("app_permission_type =", value, "appPermissionType");
            return (Criteria) this;
        }

        public Criteria andAppPermissionTypeNotEqualTo(Byte value) {
            addCriterion("app_permission_type <>", value, "appPermissionType");
            return (Criteria) this;
        }

        public Criteria andAppPermissionTypeGreaterThan(Byte value) {
            addCriterion("app_permission_type >", value, "appPermissionType");
            return (Criteria) this;
        }

        public Criteria andAppPermissionTypeGreaterThanOrEqualTo(Byte value) {
            addCriterion("app_permission_type >=", value, "appPermissionType");
            return (Criteria) this;
        }

        public Criteria andAppPermissionTypeLessThan(Byte value) {
            addCriterion("app_permission_type <", value, "appPermissionType");
            return (Criteria) this;
        }

        public Criteria andAppPermissionTypeLessThanOrEqualTo(Byte value) {
            addCriterion("app_permission_type <=", value, "appPermissionType");
            return (Criteria) this;
        }

        public Criteria andAppPermissionTypeIn(List<Byte> values) {
            addCriterion("app_permission_type in", values, "appPermissionType");
            return (Criteria) this;
        }

        public Criteria andAppPermissionTypeNotIn(List<Byte> values) {
            addCriterion("app_permission_type not in", values, "appPermissionType");
            return (Criteria) this;
        }

        public Criteria andAppPermissionTypeBetween(Byte value1, Byte value2) {
            addCriterion("app_permission_type between", value1, value2, "appPermissionType");
            return (Criteria) this;
        }

        public Criteria andAppPermissionTypeNotBetween(Byte value1, Byte value2) {
            addCriterion("app_permission_type not between", value1, value2, "appPermissionType");
            return (Criteria) this;
        }

        public Criteria andIsCheckIsNull() {
            addCriterion("is_check is null");
            return (Criteria) this;
        }

        public Criteria andIsCheckIsNotNull() {
            addCriterion("is_check is not null");
            return (Criteria) this;
        }

        public Criteria andIsCheckEqualTo(Byte value) {
            addCriterion("is_check =", value, "isCheck");
            return (Criteria) this;
        }

        public Criteria andIsCheckNotEqualTo(Byte value) {
            addCriterion("is_check <>", value, "isCheck");
            return (Criteria) this;
        }

        public Criteria andIsCheckGreaterThan(Byte value) {
            addCriterion("is_check >", value, "isCheck");
            return (Criteria) this;
        }

        public Criteria andIsCheckGreaterThanOrEqualTo(Byte value) {
            addCriterion("is_check >=", value, "isCheck");
            return (Criteria) this;
        }

        public Criteria andIsCheckLessThan(Byte value) {
            addCriterion("is_check <", value, "isCheck");
            return (Criteria) this;
        }

        public Criteria andIsCheckLessThanOrEqualTo(Byte value) {
            addCriterion("is_check <=", value, "isCheck");
            return (Criteria) this;
        }

        public Criteria andIsCheckIn(List<Byte> values) {
            addCriterion("is_check in", values, "isCheck");
            return (Criteria) this;
        }

        public Criteria andIsCheckNotIn(List<Byte> values) {
            addCriterion("is_check not in", values, "isCheck");
            return (Criteria) this;
        }

        public Criteria andIsCheckBetween(Byte value1, Byte value2) {
            addCriterion("is_check between", value1, value2, "isCheck");
            return (Criteria) this;
        }

        public Criteria andIsCheckNotBetween(Byte value1, Byte value2) {
            addCriterion("is_check not between", value1, value2, "isCheck");
            return (Criteria) this;
        }

        public Criteria andIsReadIsNull() {
            addCriterion("is_read is null");
            return (Criteria) this;
        }

        public Criteria andIsReadIsNotNull() {
            addCriterion("is_read is not null");
            return (Criteria) this;
        }

        public Criteria andIsReadEqualTo(Byte value) {
            addCriterion("is_read =", value, "isRead");
            return (Criteria) this;
        }

        public Criteria andIsReadNotEqualTo(Byte value) {
            addCriterion("is_read <>", value, "isRead");
            return (Criteria) this;
        }

        public Criteria andIsReadGreaterThan(Byte value) {
            addCriterion("is_read >", value, "isRead");
            return (Criteria) this;
        }

        public Criteria andIsReadGreaterThanOrEqualTo(Byte value) {
            addCriterion("is_read >=", value, "isRead");
            return (Criteria) this;
        }

        public Criteria andIsReadLessThan(Byte value) {
            addCriterion("is_read <", value, "isRead");
            return (Criteria) this;
        }

        public Criteria andIsReadLessThanOrEqualTo(Byte value) {
            addCriterion("is_read <=", value, "isRead");
            return (Criteria) this;
        }

        public Criteria andIsReadIn(List<Byte> values) {
            addCriterion("is_read in", values, "isRead");
            return (Criteria) this;
        }

        public Criteria andIsReadNotIn(List<Byte> values) {
            addCriterion("is_read not in", values, "isRead");
            return (Criteria) this;
        }

        public Criteria andIsReadBetween(Byte value1, Byte value2) {
            addCriterion("is_read between", value1, value2, "isRead");
            return (Criteria) this;
        }

        public Criteria andIsReadNotBetween(Byte value1, Byte value2) {
            addCriterion("is_read not between", value1, value2, "isRead");
            return (Criteria) this;
        }

        public Criteria andInputTypeIsNull() {
            addCriterion("input_type is null");
            return (Criteria) this;
        }

        public Criteria andInputTypeIsNotNull() {
            addCriterion("input_type is not null");
            return (Criteria) this;
        }

        public Criteria andInputTypeEqualTo(Byte value) {
            addCriterion("input_type =", value, "inputType");
            return (Criteria) this;
        }

        public Criteria andInputTypeNotEqualTo(Byte value) {
            addCriterion("input_type <>", value, "inputType");
            return (Criteria) this;
        }

        public Criteria andInputTypeGreaterThan(Byte value) {
            addCriterion("input_type >", value, "inputType");
            return (Criteria) this;
        }

        public Criteria andInputTypeGreaterThanOrEqualTo(Byte value) {
            addCriterion("input_type >=", value, "inputType");
            return (Criteria) this;
        }

        public Criteria andInputTypeLessThan(Byte value) {
            addCriterion("input_type <", value, "inputType");
            return (Criteria) this;
        }

        public Criteria andInputTypeLessThanOrEqualTo(Byte value) {
            addCriterion("input_type <=", value, "inputType");
            return (Criteria) this;
        }

        public Criteria andInputTypeIn(List<Byte> values) {
            addCriterion("input_type in", values, "inputType");
            return (Criteria) this;
        }

        public Criteria andInputTypeNotIn(List<Byte> values) {
            addCriterion("input_type not in", values, "inputType");
            return (Criteria) this;
        }

        public Criteria andInputTypeBetween(Byte value1, Byte value2) {
            addCriterion("input_type between", value1, value2, "inputType");
            return (Criteria) this;
        }

        public Criteria andInputTypeNotBetween(Byte value1, Byte value2) {
            addCriterion("input_type not between", value1, value2, "inputType");
            return (Criteria) this;
        }

        public Criteria andInputGroupIsNull() {
            addCriterion("input_group is null");
            return (Criteria) this;
        }

        public Criteria andInputGroupIsNotNull() {
            addCriterion("input_group is not null");
            return (Criteria) this;
        }

        public Criteria andInputGroupEqualTo(Byte value) {
            addCriterion("input_group =", value, "inputGroup");
            return (Criteria) this;
        }

        public Criteria andInputGroupNotEqualTo(Byte value) {
            addCriterion("input_group <>", value, "inputGroup");
            return (Criteria) this;
        }

        public Criteria andInputGroupGreaterThan(Byte value) {
            addCriterion("input_group >", value, "inputGroup");
            return (Criteria) this;
        }

        public Criteria andInputGroupGreaterThanOrEqualTo(Byte value) {
            addCriterion("input_group >=", value, "inputGroup");
            return (Criteria) this;
        }

        public Criteria andInputGroupLessThan(Byte value) {
            addCriterion("input_group <", value, "inputGroup");
            return (Criteria) this;
        }

        public Criteria andInputGroupLessThanOrEqualTo(Byte value) {
            addCriterion("input_group <=", value, "inputGroup");
            return (Criteria) this;
        }

        public Criteria andInputGroupIn(List<Byte> values) {
            addCriterion("input_group in", values, "inputGroup");
            return (Criteria) this;
        }

        public Criteria andInputGroupNotIn(List<Byte> values) {
            addCriterion("input_group not in", values, "inputGroup");
            return (Criteria) this;
        }

        public Criteria andInputGroupBetween(Byte value1, Byte value2) {
            addCriterion("input_group between", value1, value2, "inputGroup");
            return (Criteria) this;
        }

        public Criteria andInputGroupNotBetween(Byte value1, Byte value2) {
            addCriterion("input_group not between", value1, value2, "inputGroup");
            return (Criteria) this;
        }

        public Criteria andCreateTimeIsNull() {
            addCriterion("create_time is null");
            return (Criteria) this;
        }

        public Criteria andCreateTimeIsNotNull() {
            addCriterion("create_time is not null");
            return (Criteria) this;
        }

        public Criteria andCreateTimeEqualTo(Date value) {
            addCriterion("create_time =", value, "createTime");
            return (Criteria) this;
        }

        public Criteria andCreateTimeNotEqualTo(Date value) {
            addCriterion("create_time <>", value, "createTime");
            return (Criteria) this;
        }

        public Criteria andCreateTimeGreaterThan(Date value) {
            addCriterion("create_time >", value, "createTime");
            return (Criteria) this;
        }

        public Criteria andCreateTimeGreaterThanOrEqualTo(Date value) {
            addCriterion("create_time >=", value, "createTime");
            return (Criteria) this;
        }

        public Criteria andCreateTimeLessThan(Date value) {
            addCriterion("create_time <", value, "createTime");
            return (Criteria) this;
        }

        public Criteria andCreateTimeLessThanOrEqualTo(Date value) {
            addCriterion("create_time <=", value, "createTime");
            return (Criteria) this;
        }

        public Criteria andCreateTimeIn(List<Date> values) {
            addCriterion("create_time in", values, "createTime");
            return (Criteria) this;
        }

        public Criteria andCreateTimeNotIn(List<Date> values) {
            addCriterion("create_time not in", values, "createTime");
            return (Criteria) this;
        }

        public Criteria andCreateTimeBetween(Date value1, Date value2) {
            addCriterion("create_time between", value1, value2, "createTime");
            return (Criteria) this;
        }

        public Criteria andCreateTimeNotBetween(Date value1, Date value2) {
            addCriterion("create_time not between", value1, value2, "createTime");
            return (Criteria) this;
        }

        public Criteria andUpdateTimeIsNull() {
            addCriterion("update_time is null");
            return (Criteria) this;
        }

        public Criteria andUpdateTimeIsNotNull() {
            addCriterion("update_time is not null");
            return (Criteria) this;
        }

        public Criteria andUpdateTimeEqualTo(Date value) {
            addCriterion("update_time =", value, "updateTime");
            return (Criteria) this;
        }

        public Criteria andUpdateTimeNotEqualTo(Date value) {
            addCriterion("update_time <>", value, "updateTime");
            return (Criteria) this;
        }

        public Criteria andUpdateTimeGreaterThan(Date value) {
            addCriterion("update_time >", value, "updateTime");
            return (Criteria) this;
        }

        public Criteria andUpdateTimeGreaterThanOrEqualTo(Date value) {
            addCriterion("update_time >=", value, "updateTime");
            return (Criteria) this;
        }

        public Criteria andUpdateTimeLessThan(Date value) {
            addCriterion("update_time <", value, "updateTime");
            return (Criteria) this;
        }

        public Criteria andUpdateTimeLessThanOrEqualTo(Date value) {
            addCriterion("update_time <=", value, "updateTime");
            return (Criteria) this;
        }

        public Criteria andUpdateTimeIn(List<Date> values) {
            addCriterion("update_time in", values, "updateTime");
            return (Criteria) this;
        }

        public Criteria andUpdateTimeNotIn(List<Date> values) {
            addCriterion("update_time not in", values, "updateTime");
            return (Criteria) this;
        }

        public Criteria andUpdateTimeBetween(Date value1, Date value2) {
            addCriterion("update_time between", value1, value2, "updateTime");
            return (Criteria) this;
        }

        public Criteria andUpdateTimeNotBetween(Date value1, Date value2) {
            addCriterion("update_time not between", value1, value2, "updateTime");
            return (Criteria) this;
        }

        public Criteria andParentPermissionIsNull() {
            addCriterion("parent_permission is null");
            return (Criteria) this;
        }

        public Criteria andParentPermissionIsNotNull() {
            addCriterion("parent_permission is not null");
            return (Criteria) this;
        }

        public Criteria andParentPermissionEqualTo(String value) {
            addCriterion("parent_permission =", value, "parentPermission");
            return (Criteria) this;
        }

        public Criteria andParentPermissionNotEqualTo(String value) {
            addCriterion("parent_permission <>", value, "parentPermission");
            return (Criteria) this;
        }

        public Criteria andParentPermissionGreaterThan(String value) {
            addCriterion("parent_permission >", value, "parentPermission");
            return (Criteria) this;
        }

        public Criteria andParentPermissionGreaterThanOrEqualTo(String value) {
            addCriterion("parent_permission >=", value, "parentPermission");
            return (Criteria) this;
        }

        public Criteria andParentPermissionLessThan(String value) {
            addCriterion("parent_permission <", value, "parentPermission");
            return (Criteria) this;
        }

        public Criteria andParentPermissionLessThanOrEqualTo(String value) {
            addCriterion("parent_permission <=", value, "parentPermission");
            return (Criteria) this;
        }

        public Criteria andParentPermissionLike(String value) {
            addCriterion("parent_permission like", value, "parentPermission");
            return (Criteria) this;
        }

        public Criteria andParentPermissionNotLike(String value) {
            addCriterion("parent_permission not like", value, "parentPermission");
            return (Criteria) this;
        }

        public Criteria andParentPermissionIn(List<String> values) {
            addCriterion("parent_permission in", values, "parentPermission");
            return (Criteria) this;
        }

        public Criteria andParentPermissionNotIn(List<String> values) {
            addCriterion("parent_permission not in", values, "parentPermission");
            return (Criteria) this;
        }

        public Criteria andParentPermissionBetween(String value1, String value2) {
            addCriterion("parent_permission between", value1, value2, "parentPermission");
            return (Criteria) this;
        }

        public Criteria andParentPermissionNotBetween(String value1, String value2) {
            addCriterion("parent_permission not between", value1, value2, "parentPermission");
            return (Criteria) this;
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table tb_app_permission
     *
     * @mbggenerated do_not_delete_during_merge
     */
    public static class Criteria extends GeneratedCriteria {

        protected Criteria() {
            super();
        }

        public Criteria andAppPermissionNoLikeInsensitive(String value) {
            addCriterion("upper(app_permission_no) like", value.toUpperCase(), "appPermissionNo");
            return this;
        }

        public Criteria andAppPermissionNameLikeInsensitive(String value) {
            addCriterion("upper(app_permission_name) like", value.toUpperCase(), "appPermissionName");
            return this;
        }

        public Criteria andParentPermissionLikeInsensitive(String value) {
            addCriterion("upper(parent_permission) like", value.toUpperCase(), "parentPermission");
            return this;
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table tb_app_permission
     *
     * @mbggenerated
     */
    public static class Criterion {
        private String condition;

        private Object value;

        private Object secondValue;

        private boolean noValue;

        private boolean singleValue;

        private boolean betweenValue;

        private boolean listValue;

        public String getCondition() {
            return condition;
        }

        public Object getValue() {
            return value;
        }

        public Object getSecondValue() {
            return secondValue;
        }

        public boolean isNoValue() {
            return noValue;
        }

        public boolean isSingleValue() {
            return singleValue;
        }

        public boolean isBetweenValue() {
            return betweenValue;
        }

        public boolean isListValue() {
            return listValue;
        }

        protected Criterion(String condition) {
            super();
            this.condition = condition;
            this.noValue = true;
        }

        protected Criterion(String condition, Object value) {
            super();
            this.condition = condition;
            this.value = value;
            if (value instanceof List<?>) {
                this.listValue = true;
            } else {
                this.singleValue = true;
            }
        }

        protected Criterion(String condition, Object value, Object secondValue) {
            super();
            this.condition = condition;
            this.value = value;
            this.secondValue = secondValue;
            this.betweenValue = true;
        }
    }
}