package org.zcgewu.study.soa.service.doctor.po;

import java.io.Serializable;
import java.util.Date;

public class AppPermission implements Serializable {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_app_permission.app_permission_uid
     *
     * @mbggenerated
     */
    private Integer appPermissionUid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_app_permission.app_permission_no
     *
     * @mbggenerated
     */
    private String appPermissionNo;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_app_permission.app_permission_name
     *
     * @mbggenerated
     */
    private String appPermissionName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_app_permission.app_permission_type
     *
     * @mbggenerated
     */
    private Byte appPermissionType;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_app_permission.is_check
     *
     * @mbggenerated
     */
    private Byte isCheck;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_app_permission.is_read
     *
     * @mbggenerated
     */
    private Byte isRead;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_app_permission.input_type
     *
     * @mbggenerated
     */
    private Byte inputType;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_app_permission.input_group
     *
     * @mbggenerated
     */
    private Byte inputGroup;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_app_permission.create_time
     *
     * @mbggenerated
     */
    private Date createTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_app_permission.update_time
     *
     * @mbggenerated
     */
    private Date updateTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_app_permission.parent_permission
     *
     * @mbggenerated
     */
    private String parentPermission;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table tb_app_permission
     *
     * @mbggenerated
     */
    private static final long serialVersionUID = 1L;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_app_permission.app_permission_uid
     *
     * @return the value of tb_app_permission.app_permission_uid
     *
     * @mbggenerated
     */
    public Integer getAppPermissionUid() {
        return appPermissionUid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_app_permission.app_permission_uid
     *
     * @param appPermissionUid the value for tb_app_permission.app_permission_uid
     *
     * @mbggenerated
     */
    public void setAppPermissionUid(Integer appPermissionUid) {
        this.appPermissionUid = appPermissionUid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_app_permission.app_permission_no
     *
     * @return the value of tb_app_permission.app_permission_no
     *
     * @mbggenerated
     */
    public String getAppPermissionNo() {
        return appPermissionNo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_app_permission.app_permission_no
     *
     * @param appPermissionNo the value for tb_app_permission.app_permission_no
     *
     * @mbggenerated
     */
    public void setAppPermissionNo(String appPermissionNo) {
        this.appPermissionNo = appPermissionNo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_app_permission.app_permission_name
     *
     * @return the value of tb_app_permission.app_permission_name
     *
     * @mbggenerated
     */
    public String getAppPermissionName() {
        return appPermissionName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_app_permission.app_permission_name
     *
     * @param appPermissionName the value for tb_app_permission.app_permission_name
     *
     * @mbggenerated
     */
    public void setAppPermissionName(String appPermissionName) {
        this.appPermissionName = appPermissionName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_app_permission.app_permission_type
     *
     * @return the value of tb_app_permission.app_permission_type
     *
     * @mbggenerated
     */
    public Byte getAppPermissionType() {
        return appPermissionType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_app_permission.app_permission_type
     *
     * @param appPermissionType the value for tb_app_permission.app_permission_type
     *
     * @mbggenerated
     */
    public void setAppPermissionType(Byte appPermissionType) {
        this.appPermissionType = appPermissionType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_app_permission.is_check
     *
     * @return the value of tb_app_permission.is_check
     *
     * @mbggenerated
     */
    public Byte getIsCheck() {
        return isCheck;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_app_permission.is_check
     *
     * @param isCheck the value for tb_app_permission.is_check
     *
     * @mbggenerated
     */
    public void setIsCheck(Byte isCheck) {
        this.isCheck = isCheck;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_app_permission.is_read
     *
     * @return the value of tb_app_permission.is_read
     *
     * @mbggenerated
     */
    public Byte getIsRead() {
        return isRead;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_app_permission.is_read
     *
     * @param isRead the value for tb_app_permission.is_read
     *
     * @mbggenerated
     */
    public void setIsRead(Byte isRead) {
        this.isRead = isRead;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_app_permission.input_type
     *
     * @return the value of tb_app_permission.input_type
     *
     * @mbggenerated
     */
    public Byte getInputType() {
        return inputType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_app_permission.input_type
     *
     * @param inputType the value for tb_app_permission.input_type
     *
     * @mbggenerated
     */
    public void setInputType(Byte inputType) {
        this.inputType = inputType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_app_permission.input_group
     *
     * @return the value of tb_app_permission.input_group
     *
     * @mbggenerated
     */
    public Byte getInputGroup() {
        return inputGroup;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_app_permission.input_group
     *
     * @param inputGroup the value for tb_app_permission.input_group
     *
     * @mbggenerated
     */
    public void setInputGroup(Byte inputGroup) {
        this.inputGroup = inputGroup;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_app_permission.create_time
     *
     * @return the value of tb_app_permission.create_time
     *
     * @mbggenerated
     */
    public Date getCreateTime() {
        return createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_app_permission.create_time
     *
     * @param createTime the value for tb_app_permission.create_time
     *
     * @mbggenerated
     */
    public void setCreateTime(Date createTime) {
        this.createTime = createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_app_permission.update_time
     *
     * @return the value of tb_app_permission.update_time
     *
     * @mbggenerated
     */
    public Date getUpdateTime() {
        return updateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_app_permission.update_time
     *
     * @param updateTime the value for tb_app_permission.update_time
     *
     * @mbggenerated
     */
    public void setUpdateTime(Date updateTime) {
        this.updateTime = updateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_app_permission.parent_permission
     *
     * @return the value of tb_app_permission.parent_permission
     *
     * @mbggenerated
     */
    public String getParentPermission() {
        return parentPermission;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_app_permission.parent_permission
     *
     * @param parentPermission the value for tb_app_permission.parent_permission
     *
     * @mbggenerated
     */
    public void setParentPermission(String parentPermission) {
        this.parentPermission = parentPermission;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_app_permission
     *
     * @mbggenerated
     */
    @Override
    public boolean equals(Object that) {
        if (this == that) {
            return true;
        }
        if (that == null) {
            return false;
        }
        if (getClass() != that.getClass()) {
            return false;
        }
        AppPermission other = (AppPermission) that;
        return (this.getAppPermissionUid() == null ? other.getAppPermissionUid() == null : this.getAppPermissionUid().equals(other.getAppPermissionUid()))
            && (this.getAppPermissionNo() == null ? other.getAppPermissionNo() == null : this.getAppPermissionNo().equals(other.getAppPermissionNo()))
            && (this.getAppPermissionName() == null ? other.getAppPermissionName() == null : this.getAppPermissionName().equals(other.getAppPermissionName()))
            && (this.getAppPermissionType() == null ? other.getAppPermissionType() == null : this.getAppPermissionType().equals(other.getAppPermissionType()))
            && (this.getIsCheck() == null ? other.getIsCheck() == null : this.getIsCheck().equals(other.getIsCheck()))
            && (this.getIsRead() == null ? other.getIsRead() == null : this.getIsRead().equals(other.getIsRead()))
            && (this.getInputType() == null ? other.getInputType() == null : this.getInputType().equals(other.getInputType()))
            && (this.getInputGroup() == null ? other.getInputGroup() == null : this.getInputGroup().equals(other.getInputGroup()))
            && (this.getCreateTime() == null ? other.getCreateTime() == null : this.getCreateTime().equals(other.getCreateTime()))
            && (this.getUpdateTime() == null ? other.getUpdateTime() == null : this.getUpdateTime().equals(other.getUpdateTime()))
            && (this.getParentPermission() == null ? other.getParentPermission() == null : this.getParentPermission().equals(other.getParentPermission()));
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_app_permission
     *
     * @mbggenerated
     */
    @Override
    public int hashCode() {
        final int prime = 31;
        int result = 1;
        result = prime * result + ((getAppPermissionUid() == null) ? 0 : getAppPermissionUid().hashCode());
        result = prime * result + ((getAppPermissionNo() == null) ? 0 : getAppPermissionNo().hashCode());
        result = prime * result + ((getAppPermissionName() == null) ? 0 : getAppPermissionName().hashCode());
        result = prime * result + ((getAppPermissionType() == null) ? 0 : getAppPermissionType().hashCode());
        result = prime * result + ((getIsCheck() == null) ? 0 : getIsCheck().hashCode());
        result = prime * result + ((getIsRead() == null) ? 0 : getIsRead().hashCode());
        result = prime * result + ((getInputType() == null) ? 0 : getInputType().hashCode());
        result = prime * result + ((getInputGroup() == null) ? 0 : getInputGroup().hashCode());
        result = prime * result + ((getCreateTime() == null) ? 0 : getCreateTime().hashCode());
        result = prime * result + ((getUpdateTime() == null) ? 0 : getUpdateTime().hashCode());
        result = prime * result + ((getParentPermission() == null) ? 0 : getParentPermission().hashCode());
        return result;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_app_permission
     *
     * @mbggenerated
     */
    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder();
        sb.append(getClass().getSimpleName());
        sb.append(" [");
        sb.append("Hash = ").append(hashCode());
        sb.append(", appPermissionUid=").append(appPermissionUid);
        sb.append(", appPermissionNo=").append(appPermissionNo);
        sb.append(", appPermissionName=").append(appPermissionName);
        sb.append(", appPermissionType=").append(appPermissionType);
        sb.append(", isCheck=").append(isCheck);
        sb.append(", isRead=").append(isRead);
        sb.append(", inputType=").append(inputType);
        sb.append(", inputGroup=").append(inputGroup);
        sb.append(", createTime=").append(createTime);
        sb.append(", updateTime=").append(updateTime);
        sb.append(", parentPermission=").append(parentPermission);
        sb.append(", serialVersionUID=").append(serialVersionUID);
        sb.append("]");
        return sb.toString();
    }
}