package org.zcgewu.study.soa.service.doctor.po;

import java.io.Serializable;
import java.util.Date;

public class Doctor implements Serializable {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_doctor.DoctorUID
     *
     * @mbggenerated
     */
    private Integer doctorUID;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_doctor.HospitalUID
     *
     * @mbggenerated
     */
    private Integer hospitalUID;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_doctor.RtisDoctorUID
     *
     * @mbggenerated
     */
    private String rtisDoctorUID;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_doctor.Password
     *
     * @mbggenerated
     */
    private String password;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_doctor.DoctorName
     *
     * @mbggenerated
     */
    private String doctorName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_doctor.NativePlace
     *
     * @mbggenerated
     */
    private String nativePlace;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_doctor.Birthday
     *
     * @mbggenerated
     */
    private Date birthday;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_doctor.Nationality
     *
     * @mbggenerated
     */
    private String nationality;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_doctor.StationaryPhone
     *
     * @mbggenerated
     */
    private String stationaryPhone;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_doctor.Address
     *
     * @mbggenerated
     */
    private String address;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_doctor.PicturlURL
     *
     * @mbggenerated
     */
    private String picturlURL;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_doctor.Age
     *
     * @mbggenerated
     */
    private Short age;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_doctor.Sex
     *
     * @mbggenerated
     */
    private String sex;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_doctor.IDNumber
     *
     * @mbggenerated
     */
    private String IDNumber;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_doctor.CellPhone
     *
     * @mbggenerated
     */
    private String cellPhone;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_doctor.AppCellPhone
     *
     * @mbggenerated
     */
    private String appCellPhone;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_doctor.TechnicalPostUID
     *
     * @mbggenerated
     */
    private Integer technicalPostUID;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_doctor.PositionUID
     *
     * @mbggenerated
     */
    private Integer positionUID;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_doctor.OccupationUID
     *
     * @mbggenerated
     */
    private Integer occupationUID;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_doctor.DepartmentUID
     *
     * @mbggenerated
     */
    private Integer departmentUID;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_doctor.OccupationStatusUID
     *
     * @mbggenerated
     */
    private Integer occupationStatusUID;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_doctor.Specialty
     *
     * @mbggenerated
     */
    private String specialty;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_doctor.Introduce
     *
     * @mbggenerated
     */
    private String introduce;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_doctor.CashSetUID
     *
     * @mbggenerated
     */
    private Integer cashSetUID;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_doctor.CashTypeUID
     *
     * @mbggenerated
     */
    private Integer cashTypeUID;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_doctor.Status
     *
     * @mbggenerated
     */
    private Byte status;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_doctor.IsSystemRegistered
     *
     * @mbggenerated
     */
    private Byte isSystemRegistered;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_doctor.token
     *
     * @mbggenerated
     */
    private String token;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_doctor.CreateTime
     *
     * @mbggenerated
     */
    private Date createTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_doctor.Number
     *
     * @mbggenerated
     */
    private String number;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_doctor.DisableCause
     *
     * @mbggenerated
     */
    private String disableCause;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_doctor.IsDeleted
     *
     * @mbggenerated
     */
    private Byte isDeleted;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_doctor.MedicalGroupUID
     *
     * @mbggenerated
     */
    private Integer medicalGroupUID;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_doctor.GroupPositionUID
     *
     * @mbggenerated
     */
    private Integer groupPositionUID;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_doctor.AesKey
     *
     * @mbggenerated
     */
    private String aesKey;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_doctor.TotalScore
     *
     * @mbggenerated
     */
    private Integer totalScore;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_doctor.RegisterTime
     *
     * @mbggenerated
     */
    private Date registerTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table tb_doctor
     *
     * @mbggenerated
     */
    private static final long serialVersionUID = 1L;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_doctor.DoctorUID
     *
     * @return the value of tb_doctor.DoctorUID
     *
     * @mbggenerated
     */
    public Integer getDoctorUID() {
        return doctorUID;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_doctor.DoctorUID
     *
     * @param doctorUID the value for tb_doctor.DoctorUID
     *
     * @mbggenerated
     */
    public void setDoctorUID(Integer doctorUID) {
        this.doctorUID = doctorUID;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_doctor.HospitalUID
     *
     * @return the value of tb_doctor.HospitalUID
     *
     * @mbggenerated
     */
    public Integer getHospitalUID() {
        return hospitalUID;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_doctor.HospitalUID
     *
     * @param hospitalUID the value for tb_doctor.HospitalUID
     *
     * @mbggenerated
     */
    public void setHospitalUID(Integer hospitalUID) {
        this.hospitalUID = hospitalUID;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_doctor.RtisDoctorUID
     *
     * @return the value of tb_doctor.RtisDoctorUID
     *
     * @mbggenerated
     */
    public String getRtisDoctorUID() {
        return rtisDoctorUID;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_doctor.RtisDoctorUID
     *
     * @param rtisDoctorUID the value for tb_doctor.RtisDoctorUID
     *
     * @mbggenerated
     */
    public void setRtisDoctorUID(String rtisDoctorUID) {
        this.rtisDoctorUID = rtisDoctorUID;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_doctor.Password
     *
     * @return the value of tb_doctor.Password
     *
     * @mbggenerated
     */
    public String getPassword() {
        return password;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_doctor.Password
     *
     * @param password the value for tb_doctor.Password
     *
     * @mbggenerated
     */
    public void setPassword(String password) {
        this.password = password;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_doctor.DoctorName
     *
     * @return the value of tb_doctor.DoctorName
     *
     * @mbggenerated
     */
    public String getDoctorName() {
        return doctorName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_doctor.DoctorName
     *
     * @param doctorName the value for tb_doctor.DoctorName
     *
     * @mbggenerated
     */
    public void setDoctorName(String doctorName) {
        this.doctorName = doctorName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_doctor.NativePlace
     *
     * @return the value of tb_doctor.NativePlace
     *
     * @mbggenerated
     */
    public String getNativePlace() {
        return nativePlace;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_doctor.NativePlace
     *
     * @param nativePlace the value for tb_doctor.NativePlace
     *
     * @mbggenerated
     */
    public void setNativePlace(String nativePlace) {
        this.nativePlace = nativePlace;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_doctor.Birthday
     *
     * @return the value of tb_doctor.Birthday
     *
     * @mbggenerated
     */
    public Date getBirthday() {
        return birthday;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_doctor.Birthday
     *
     * @param birthday the value for tb_doctor.Birthday
     *
     * @mbggenerated
     */
    public void setBirthday(Date birthday) {
        this.birthday = birthday;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_doctor.Nationality
     *
     * @return the value of tb_doctor.Nationality
     *
     * @mbggenerated
     */
    public String getNationality() {
        return nationality;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_doctor.Nationality
     *
     * @param nationality the value for tb_doctor.Nationality
     *
     * @mbggenerated
     */
    public void setNationality(String nationality) {
        this.nationality = nationality;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_doctor.StationaryPhone
     *
     * @return the value of tb_doctor.StationaryPhone
     *
     * @mbggenerated
     */
    public String getStationaryPhone() {
        return stationaryPhone;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_doctor.StationaryPhone
     *
     * @param stationaryPhone the value for tb_doctor.StationaryPhone
     *
     * @mbggenerated
     */
    public void setStationaryPhone(String stationaryPhone) {
        this.stationaryPhone = stationaryPhone;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_doctor.Address
     *
     * @return the value of tb_doctor.Address
     *
     * @mbggenerated
     */
    public String getAddress() {
        return address;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_doctor.Address
     *
     * @param address the value for tb_doctor.Address
     *
     * @mbggenerated
     */
    public void setAddress(String address) {
        this.address = address;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_doctor.PicturlURL
     *
     * @return the value of tb_doctor.PicturlURL
     *
     * @mbggenerated
     */
    public String getPicturlURL() {
        return picturlURL;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_doctor.PicturlURL
     *
     * @param picturlURL the value for tb_doctor.PicturlURL
     *
     * @mbggenerated
     */
    public void setPicturlURL(String picturlURL) {
        this.picturlURL = picturlURL;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_doctor.Age
     *
     * @return the value of tb_doctor.Age
     *
     * @mbggenerated
     */
    public Short getAge() {
        return age;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_doctor.Age
     *
     * @param age the value for tb_doctor.Age
     *
     * @mbggenerated
     */
    public void setAge(Short age) {
        this.age = age;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_doctor.Sex
     *
     * @return the value of tb_doctor.Sex
     *
     * @mbggenerated
     */
    public String getSex() {
        return sex;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_doctor.Sex
     *
     * @param sex the value for tb_doctor.Sex
     *
     * @mbggenerated
     */
    public void setSex(String sex) {
        this.sex = sex;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_doctor.IDNumber
     *
     * @return the value of tb_doctor.IDNumber
     *
     * @mbggenerated
     */
    public String getIDNumber() {
        return IDNumber;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_doctor.IDNumber
     *
     * @param IDNumber the value for tb_doctor.IDNumber
     *
     * @mbggenerated
     */
    public void setIDNumber(String IDNumber) {
        this.IDNumber = IDNumber;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_doctor.CellPhone
     *
     * @return the value of tb_doctor.CellPhone
     *
     * @mbggenerated
     */
    public String getCellPhone() {
        return cellPhone;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_doctor.CellPhone
     *
     * @param cellPhone the value for tb_doctor.CellPhone
     *
     * @mbggenerated
     */
    public void setCellPhone(String cellPhone) {
        this.cellPhone = cellPhone;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_doctor.AppCellPhone
     *
     * @return the value of tb_doctor.AppCellPhone
     *
     * @mbggenerated
     */
    public String getAppCellPhone() {
        return appCellPhone;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_doctor.AppCellPhone
     *
     * @param appCellPhone the value for tb_doctor.AppCellPhone
     *
     * @mbggenerated
     */
    public void setAppCellPhone(String appCellPhone) {
        this.appCellPhone = appCellPhone;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_doctor.TechnicalPostUID
     *
     * @return the value of tb_doctor.TechnicalPostUID
     *
     * @mbggenerated
     */
    public Integer getTechnicalPostUID() {
        return technicalPostUID;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_doctor.TechnicalPostUID
     *
     * @param technicalPostUID the value for tb_doctor.TechnicalPostUID
     *
     * @mbggenerated
     */
    public void setTechnicalPostUID(Integer technicalPostUID) {
        this.technicalPostUID = technicalPostUID;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_doctor.PositionUID
     *
     * @return the value of tb_doctor.PositionUID
     *
     * @mbggenerated
     */
    public Integer getPositionUID() {
        return positionUID;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_doctor.PositionUID
     *
     * @param positionUID the value for tb_doctor.PositionUID
     *
     * @mbggenerated
     */
    public void setPositionUID(Integer positionUID) {
        this.positionUID = positionUID;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_doctor.OccupationUID
     *
     * @return the value of tb_doctor.OccupationUID
     *
     * @mbggenerated
     */
    public Integer getOccupationUID() {
        return occupationUID;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_doctor.OccupationUID
     *
     * @param occupationUID the value for tb_doctor.OccupationUID
     *
     * @mbggenerated
     */
    public void setOccupationUID(Integer occupationUID) {
        this.occupationUID = occupationUID;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_doctor.DepartmentUID
     *
     * @return the value of tb_doctor.DepartmentUID
     *
     * @mbggenerated
     */
    public Integer getDepartmentUID() {
        return departmentUID;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_doctor.DepartmentUID
     *
     * @param departmentUID the value for tb_doctor.DepartmentUID
     *
     * @mbggenerated
     */
    public void setDepartmentUID(Integer departmentUID) {
        this.departmentUID = departmentUID;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_doctor.OccupationStatusUID
     *
     * @return the value of tb_doctor.OccupationStatusUID
     *
     * @mbggenerated
     */
    public Integer getOccupationStatusUID() {
        return occupationStatusUID;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_doctor.OccupationStatusUID
     *
     * @param occupationStatusUID the value for tb_doctor.OccupationStatusUID
     *
     * @mbggenerated
     */
    public void setOccupationStatusUID(Integer occupationStatusUID) {
        this.occupationStatusUID = occupationStatusUID;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_doctor.Specialty
     *
     * @return the value of tb_doctor.Specialty
     *
     * @mbggenerated
     */
    public String getSpecialty() {
        return specialty;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_doctor.Specialty
     *
     * @param specialty the value for tb_doctor.Specialty
     *
     * @mbggenerated
     */
    public void setSpecialty(String specialty) {
        this.specialty = specialty;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_doctor.Introduce
     *
     * @return the value of tb_doctor.Introduce
     *
     * @mbggenerated
     */
    public String getIntroduce() {
        return introduce;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_doctor.Introduce
     *
     * @param introduce the value for tb_doctor.Introduce
     *
     * @mbggenerated
     */
    public void setIntroduce(String introduce) {
        this.introduce = introduce;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_doctor.CashSetUID
     *
     * @return the value of tb_doctor.CashSetUID
     *
     * @mbggenerated
     */
    public Integer getCashSetUID() {
        return cashSetUID;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_doctor.CashSetUID
     *
     * @param cashSetUID the value for tb_doctor.CashSetUID
     *
     * @mbggenerated
     */
    public void setCashSetUID(Integer cashSetUID) {
        this.cashSetUID = cashSetUID;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_doctor.CashTypeUID
     *
     * @return the value of tb_doctor.CashTypeUID
     *
     * @mbggenerated
     */
    public Integer getCashTypeUID() {
        return cashTypeUID;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_doctor.CashTypeUID
     *
     * @param cashTypeUID the value for tb_doctor.CashTypeUID
     *
     * @mbggenerated
     */
    public void setCashTypeUID(Integer cashTypeUID) {
        this.cashTypeUID = cashTypeUID;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_doctor.Status
     *
     * @return the value of tb_doctor.Status
     *
     * @mbggenerated
     */
    public Byte getStatus() {
        return status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_doctor.Status
     *
     * @param status the value for tb_doctor.Status
     *
     * @mbggenerated
     */
    public void setStatus(Byte status) {
        this.status = status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_doctor.IsSystemRegistered
     *
     * @return the value of tb_doctor.IsSystemRegistered
     *
     * @mbggenerated
     */
    public Byte getIsSystemRegistered() {
        return isSystemRegistered;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_doctor.IsSystemRegistered
     *
     * @param isSystemRegistered the value for tb_doctor.IsSystemRegistered
     *
     * @mbggenerated
     */
    public void setIsSystemRegistered(Byte isSystemRegistered) {
        this.isSystemRegistered = isSystemRegistered;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_doctor.token
     *
     * @return the value of tb_doctor.token
     *
     * @mbggenerated
     */
    public String getToken() {
        return token;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_doctor.token
     *
     * @param token the value for tb_doctor.token
     *
     * @mbggenerated
     */
    public void setToken(String token) {
        this.token = token;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_doctor.CreateTime
     *
     * @return the value of tb_doctor.CreateTime
     *
     * @mbggenerated
     */
    public Date getCreateTime() {
        return createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_doctor.CreateTime
     *
     * @param createTime the value for tb_doctor.CreateTime
     *
     * @mbggenerated
     */
    public void setCreateTime(Date createTime) {
        this.createTime = createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_doctor.Number
     *
     * @return the value of tb_doctor.Number
     *
     * @mbggenerated
     */
    public String getNumber() {
        return number;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_doctor.Number
     *
     * @param number the value for tb_doctor.Number
     *
     * @mbggenerated
     */
    public void setNumber(String number) {
        this.number = number;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_doctor.DisableCause
     *
     * @return the value of tb_doctor.DisableCause
     *
     * @mbggenerated
     */
    public String getDisableCause() {
        return disableCause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_doctor.DisableCause
     *
     * @param disableCause the value for tb_doctor.DisableCause
     *
     * @mbggenerated
     */
    public void setDisableCause(String disableCause) {
        this.disableCause = disableCause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_doctor.IsDeleted
     *
     * @return the value of tb_doctor.IsDeleted
     *
     * @mbggenerated
     */
    public Byte getIsDeleted() {
        return isDeleted;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_doctor.IsDeleted
     *
     * @param isDeleted the value for tb_doctor.IsDeleted
     *
     * @mbggenerated
     */
    public void setIsDeleted(Byte isDeleted) {
        this.isDeleted = isDeleted;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_doctor.MedicalGroupUID
     *
     * @return the value of tb_doctor.MedicalGroupUID
     *
     * @mbggenerated
     */
    public Integer getMedicalGroupUID() {
        return medicalGroupUID;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_doctor.MedicalGroupUID
     *
     * @param medicalGroupUID the value for tb_doctor.MedicalGroupUID
     *
     * @mbggenerated
     */
    public void setMedicalGroupUID(Integer medicalGroupUID) {
        this.medicalGroupUID = medicalGroupUID;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_doctor.GroupPositionUID
     *
     * @return the value of tb_doctor.GroupPositionUID
     *
     * @mbggenerated
     */
    public Integer getGroupPositionUID() {
        return groupPositionUID;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_doctor.GroupPositionUID
     *
     * @param groupPositionUID the value for tb_doctor.GroupPositionUID
     *
     * @mbggenerated
     */
    public void setGroupPositionUID(Integer groupPositionUID) {
        this.groupPositionUID = groupPositionUID;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_doctor.AesKey
     *
     * @return the value of tb_doctor.AesKey
     *
     * @mbggenerated
     */
    public String getAesKey() {
        return aesKey;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_doctor.AesKey
     *
     * @param aesKey the value for tb_doctor.AesKey
     *
     * @mbggenerated
     */
    public void setAesKey(String aesKey) {
        this.aesKey = aesKey;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_doctor.TotalScore
     *
     * @return the value of tb_doctor.TotalScore
     *
     * @mbggenerated
     */
    public Integer getTotalScore() {
        return totalScore;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_doctor.TotalScore
     *
     * @param totalScore the value for tb_doctor.TotalScore
     *
     * @mbggenerated
     */
    public void setTotalScore(Integer totalScore) {
        this.totalScore = totalScore;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_doctor.RegisterTime
     *
     * @return the value of tb_doctor.RegisterTime
     *
     * @mbggenerated
     */
    public Date getRegisterTime() {
        return registerTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_doctor.RegisterTime
     *
     * @param registerTime the value for tb_doctor.RegisterTime
     *
     * @mbggenerated
     */
    public void setRegisterTime(Date registerTime) {
        this.registerTime = registerTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_doctor
     *
     * @mbggenerated
     */
    @Override
    public boolean equals(Object that) {
        if (this == that) {
            return true;
        }
        if (that == null) {
            return false;
        }
        if (getClass() != that.getClass()) {
            return false;
        }
        Doctor other = (Doctor) that;
        return (this.getDoctorUID() == null ? other.getDoctorUID() == null : this.getDoctorUID().equals(other.getDoctorUID()))
            && (this.getHospitalUID() == null ? other.getHospitalUID() == null : this.getHospitalUID().equals(other.getHospitalUID()))
            && (this.getRtisDoctorUID() == null ? other.getRtisDoctorUID() == null : this.getRtisDoctorUID().equals(other.getRtisDoctorUID()))
            && (this.getPassword() == null ? other.getPassword() == null : this.getPassword().equals(other.getPassword()))
            && (this.getDoctorName() == null ? other.getDoctorName() == null : this.getDoctorName().equals(other.getDoctorName()))
            && (this.getNativePlace() == null ? other.getNativePlace() == null : this.getNativePlace().equals(other.getNativePlace()))
            && (this.getBirthday() == null ? other.getBirthday() == null : this.getBirthday().equals(other.getBirthday()))
            && (this.getNationality() == null ? other.getNationality() == null : this.getNationality().equals(other.getNationality()))
            && (this.getStationaryPhone() == null ? other.getStationaryPhone() == null : this.getStationaryPhone().equals(other.getStationaryPhone()))
            && (this.getAddress() == null ? other.getAddress() == null : this.getAddress().equals(other.getAddress()))
            && (this.getPicturlURL() == null ? other.getPicturlURL() == null : this.getPicturlURL().equals(other.getPicturlURL()))
            && (this.getAge() == null ? other.getAge() == null : this.getAge().equals(other.getAge()))
            && (this.getSex() == null ? other.getSex() == null : this.getSex().equals(other.getSex()))
            && (this.getIDNumber() == null ? other.getIDNumber() == null : this.getIDNumber().equals(other.getIDNumber()))
            && (this.getCellPhone() == null ? other.getCellPhone() == null : this.getCellPhone().equals(other.getCellPhone()))
            && (this.getAppCellPhone() == null ? other.getAppCellPhone() == null : this.getAppCellPhone().equals(other.getAppCellPhone()))
            && (this.getTechnicalPostUID() == null ? other.getTechnicalPostUID() == null : this.getTechnicalPostUID().equals(other.getTechnicalPostUID()))
            && (this.getPositionUID() == null ? other.getPositionUID() == null : this.getPositionUID().equals(other.getPositionUID()))
            && (this.getOccupationUID() == null ? other.getOccupationUID() == null : this.getOccupationUID().equals(other.getOccupationUID()))
            && (this.getDepartmentUID() == null ? other.getDepartmentUID() == null : this.getDepartmentUID().equals(other.getDepartmentUID()))
            && (this.getOccupationStatusUID() == null ? other.getOccupationStatusUID() == null : this.getOccupationStatusUID().equals(other.getOccupationStatusUID()))
            && (this.getSpecialty() == null ? other.getSpecialty() == null : this.getSpecialty().equals(other.getSpecialty()))
            && (this.getIntroduce() == null ? other.getIntroduce() == null : this.getIntroduce().equals(other.getIntroduce()))
            && (this.getCashSetUID() == null ? other.getCashSetUID() == null : this.getCashSetUID().equals(other.getCashSetUID()))
            && (this.getCashTypeUID() == null ? other.getCashTypeUID() == null : this.getCashTypeUID().equals(other.getCashTypeUID()))
            && (this.getStatus() == null ? other.getStatus() == null : this.getStatus().equals(other.getStatus()))
            && (this.getIsSystemRegistered() == null ? other.getIsSystemRegistered() == null : this.getIsSystemRegistered().equals(other.getIsSystemRegistered()))
            && (this.getToken() == null ? other.getToken() == null : this.getToken().equals(other.getToken()))
            && (this.getCreateTime() == null ? other.getCreateTime() == null : this.getCreateTime().equals(other.getCreateTime()))
            && (this.getNumber() == null ? other.getNumber() == null : this.getNumber().equals(other.getNumber()))
            && (this.getDisableCause() == null ? other.getDisableCause() == null : this.getDisableCause().equals(other.getDisableCause()))
            && (this.getIsDeleted() == null ? other.getIsDeleted() == null : this.getIsDeleted().equals(other.getIsDeleted()))
            && (this.getMedicalGroupUID() == null ? other.getMedicalGroupUID() == null : this.getMedicalGroupUID().equals(other.getMedicalGroupUID()))
            && (this.getGroupPositionUID() == null ? other.getGroupPositionUID() == null : this.getGroupPositionUID().equals(other.getGroupPositionUID()))
            && (this.getAesKey() == null ? other.getAesKey() == null : this.getAesKey().equals(other.getAesKey()))
            && (this.getTotalScore() == null ? other.getTotalScore() == null : this.getTotalScore().equals(other.getTotalScore()))
            && (this.getRegisterTime() == null ? other.getRegisterTime() == null : this.getRegisterTime().equals(other.getRegisterTime()));
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_doctor
     *
     * @mbggenerated
     */
    @Override
    public int hashCode() {
        final int prime = 31;
        int result = 1;
        result = prime * result + ((getDoctorUID() == null) ? 0 : getDoctorUID().hashCode());
        result = prime * result + ((getHospitalUID() == null) ? 0 : getHospitalUID().hashCode());
        result = prime * result + ((getRtisDoctorUID() == null) ? 0 : getRtisDoctorUID().hashCode());
        result = prime * result + ((getPassword() == null) ? 0 : getPassword().hashCode());
        result = prime * result + ((getDoctorName() == null) ? 0 : getDoctorName().hashCode());
        result = prime * result + ((getNativePlace() == null) ? 0 : getNativePlace().hashCode());
        result = prime * result + ((getBirthday() == null) ? 0 : getBirthday().hashCode());
        result = prime * result + ((getNationality() == null) ? 0 : getNationality().hashCode());
        result = prime * result + ((getStationaryPhone() == null) ? 0 : getStationaryPhone().hashCode());
        result = prime * result + ((getAddress() == null) ? 0 : getAddress().hashCode());
        result = prime * result + ((getPicturlURL() == null) ? 0 : getPicturlURL().hashCode());
        result = prime * result + ((getAge() == null) ? 0 : getAge().hashCode());
        result = prime * result + ((getSex() == null) ? 0 : getSex().hashCode());
        result = prime * result + ((getIDNumber() == null) ? 0 : getIDNumber().hashCode());
        result = prime * result + ((getCellPhone() == null) ? 0 : getCellPhone().hashCode());
        result = prime * result + ((getAppCellPhone() == null) ? 0 : getAppCellPhone().hashCode());
        result = prime * result + ((getTechnicalPostUID() == null) ? 0 : getTechnicalPostUID().hashCode());
        result = prime * result + ((getPositionUID() == null) ? 0 : getPositionUID().hashCode());
        result = prime * result + ((getOccupationUID() == null) ? 0 : getOccupationUID().hashCode());
        result = prime * result + ((getDepartmentUID() == null) ? 0 : getDepartmentUID().hashCode());
        result = prime * result + ((getOccupationStatusUID() == null) ? 0 : getOccupationStatusUID().hashCode());
        result = prime * result + ((getSpecialty() == null) ? 0 : getSpecialty().hashCode());
        result = prime * result + ((getIntroduce() == null) ? 0 : getIntroduce().hashCode());
        result = prime * result + ((getCashSetUID() == null) ? 0 : getCashSetUID().hashCode());
        result = prime * result + ((getCashTypeUID() == null) ? 0 : getCashTypeUID().hashCode());
        result = prime * result + ((getStatus() == null) ? 0 : getStatus().hashCode());
        result = prime * result + ((getIsSystemRegistered() == null) ? 0 : getIsSystemRegistered().hashCode());
        result = prime * result + ((getToken() == null) ? 0 : getToken().hashCode());
        result = prime * result + ((getCreateTime() == null) ? 0 : getCreateTime().hashCode());
        result = prime * result + ((getNumber() == null) ? 0 : getNumber().hashCode());
        result = prime * result + ((getDisableCause() == null) ? 0 : getDisableCause().hashCode());
        result = prime * result + ((getIsDeleted() == null) ? 0 : getIsDeleted().hashCode());
        result = prime * result + ((getMedicalGroupUID() == null) ? 0 : getMedicalGroupUID().hashCode());
        result = prime * result + ((getGroupPositionUID() == null) ? 0 : getGroupPositionUID().hashCode());
        result = prime * result + ((getAesKey() == null) ? 0 : getAesKey().hashCode());
        result = prime * result + ((getTotalScore() == null) ? 0 : getTotalScore().hashCode());
        result = prime * result + ((getRegisterTime() == null) ? 0 : getRegisterTime().hashCode());
        return result;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_doctor
     *
     * @mbggenerated
     */
    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder();
        sb.append(getClass().getSimpleName());
        sb.append(" [");
        sb.append("Hash = ").append(hashCode());
        sb.append(", doctorUID=").append(doctorUID);
        sb.append(", hospitalUID=").append(hospitalUID);
        sb.append(", rtisDoctorUID=").append(rtisDoctorUID);
        sb.append(", password=").append(password);
        sb.append(", doctorName=").append(doctorName);
        sb.append(", nativePlace=").append(nativePlace);
        sb.append(", birthday=").append(birthday);
        sb.append(", nationality=").append(nationality);
        sb.append(", stationaryPhone=").append(stationaryPhone);
        sb.append(", address=").append(address);
        sb.append(", picturlURL=").append(picturlURL);
        sb.append(", age=").append(age);
        sb.append(", sex=").append(sex);
        sb.append(", IDNumber=").append(IDNumber);
        sb.append(", cellPhone=").append(cellPhone);
        sb.append(", appCellPhone=").append(appCellPhone);
        sb.append(", technicalPostUID=").append(technicalPostUID);
        sb.append(", positionUID=").append(positionUID);
        sb.append(", occupationUID=").append(occupationUID);
        sb.append(", departmentUID=").append(departmentUID);
        sb.append(", occupationStatusUID=").append(occupationStatusUID);
        sb.append(", specialty=").append(specialty);
        sb.append(", introduce=").append(introduce);
        sb.append(", cashSetUID=").append(cashSetUID);
        sb.append(", cashTypeUID=").append(cashTypeUID);
        sb.append(", status=").append(status);
        sb.append(", isSystemRegistered=").append(isSystemRegistered);
        sb.append(", token=").append(token);
        sb.append(", createTime=").append(createTime);
        sb.append(", number=").append(number);
        sb.append(", disableCause=").append(disableCause);
        sb.append(", isDeleted=").append(isDeleted);
        sb.append(", medicalGroupUID=").append(medicalGroupUID);
        sb.append(", groupPositionUID=").append(groupPositionUID);
        sb.append(", aesKey=").append(aesKey);
        sb.append(", totalScore=").append(totalScore);
        sb.append(", registerTime=").append(registerTime);
        sb.append(", serialVersionUID=").append(serialVersionUID);
        sb.append("]");
        return sb.toString();
    }
}