package org.zcgewu.study.soa.service.doctor.mapper;

import java.util.List;
import org.apache.ibatis.annotations.Param;
import org.zcgewu.study.soa.service.doctor.po.DoctorAppRole;
import org.zcgewu.study.soa.service.doctor.po.DoctorAppRoleExample;

public interface DoctorAppRoleMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_doctor_app_role
     *
     * @mbggenerated
     */
    int countByExample(DoctorAppRoleExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_doctor_app_role
     *
     * @mbggenerated
     */
    int deleteByExample(DoctorAppRoleExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_doctor_app_role
     *
     * @mbggenerated
     */
    int deleteByPrimaryKey(Integer doctorAppRoleUid);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_doctor_app_role
     *
     * @mbggenerated
     */
    int insert(DoctorAppRole record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_doctor_app_role
     *
     * @mbggenerated
     */
    int insertSelective(DoctorAppRole record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_doctor_app_role
     *
     * @mbggenerated
     */
    List<DoctorAppRole> selectByExample(DoctorAppRoleExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_doctor_app_role
     *
     * @mbggenerated
     */
    DoctorAppRole selectByPrimaryKey(Integer doctorAppRoleUid);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_doctor_app_role
     *
     * @mbggenerated
     */
    int updateByExampleSelective(@Param("record") DoctorAppRole record, @Param("example") DoctorAppRoleExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_doctor_app_role
     *
     * @mbggenerated
     */
    int updateByExample(@Param("record") DoctorAppRole record, @Param("example") DoctorAppRoleExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_doctor_app_role
     *
     * @mbggenerated
     */
    int updateByPrimaryKeySelective(DoctorAppRole record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_doctor_app_role
     *
     * @mbggenerated
     */
    int updateByPrimaryKey(DoctorAppRole record);
}