package org.zcgewu.study.soa.doctor.mapper;

import java.util.List;
import org.apache.ibatis.annotations.Param;
import org.zcgewu.study.soa.doctor.po.AppPermission;
import org.zcgewu.study.soa.doctor.po.AppPermissionExample;

public interface AppPermissionMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_app_permission
     *
     * @mbggenerated
     */
    int countByExample(AppPermissionExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_app_permission
     *
     * @mbggenerated
     */
    int deleteByExample(AppPermissionExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_app_permission
     *
     * @mbggenerated
     */
    int deleteByPrimaryKey(Integer appPermissionUid);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_app_permission
     *
     * @mbggenerated
     */
    int insert(AppPermission record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_app_permission
     *
     * @mbggenerated
     */
    int insertSelective(AppPermission record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_app_permission
     *
     * @mbggenerated
     */
    List<AppPermission> selectByExample(AppPermissionExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_app_permission
     *
     * @mbggenerated
     */
    AppPermission selectByPrimaryKey(Integer appPermissionUid);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_app_permission
     *
     * @mbggenerated
     */
    int updateByExampleSelective(@Param("record") AppPermission record, @Param("example") AppPermissionExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_app_permission
     *
     * @mbggenerated
     */
    int updateByExample(@Param("record") AppPermission record, @Param("example") AppPermissionExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_app_permission
     *
     * @mbggenerated
     */
    int updateByPrimaryKeySelective(AppPermission record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_app_permission
     *
     * @mbggenerated
     */
    int updateByPrimaryKey(AppPermission record);
}