package org.zcgewu.study.soa.doctor.mapper;

import java.util.List;
import org.apache.ibatis.annotations.Param;
import org.zcgewu.study.soa.doctor.po.Doctor;
import org.zcgewu.study.soa.doctor.po.DoctorExample;

public interface DoctorMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_doctor
     *
     * @mbggenerated
     */
    int countByExample(DoctorExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_doctor
     *
     * @mbggenerated
     */
    int deleteByExample(DoctorExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_doctor
     *
     * @mbggenerated
     */
    int deleteByPrimaryKey(Integer doctorUID);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_doctor
     *
     * @mbggenerated
     */
    int insert(Doctor record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_doctor
     *
     * @mbggenerated
     */
    int insertSelective(Doctor record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_doctor
     *
     * @mbggenerated
     */
    List<Doctor> selectByExample(DoctorExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_doctor
     *
     * @mbggenerated
     */
    Doctor selectByPrimaryKey(Integer doctorUID);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_doctor
     *
     * @mbggenerated
     */
    int updateByExampleSelective(@Param("record") Doctor record, @Param("example") DoctorExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_doctor
     *
     * @mbggenerated
     */
    int updateByExample(@Param("record") Doctor record, @Param("example") DoctorExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_doctor
     *
     * @mbggenerated
     */
    int updateByPrimaryKeySelective(Doctor record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_doctor
     *
     * @mbggenerated
     */
    int updateByPrimaryKey(Doctor record);
}